Macaulay2 Engine: GBRing::gbvector_mult_by_term
gbvector_mult_by_term()
void GBRing::gbvector_mult_by_term (const FreeModule * F, const FreeModule * Fsyz, ring_elem a, const int * m, const gbvector * f, const gbvector * fsyz, gbvector *& result, gbvector *& esult_syz)
Definition at line 846 of file gbring.cpp.
 {
   // TODO
   // The reason this has both result,result_syz together is in case we want to
   //   reduce result_fsyz mod a quotient ideal.  Do we really need to do this as
   //   we go?  This will require experimentation.
   result = mult_by_term(F, f, a, m, 0);
   result_syz = mult_by_term(Fsyz, fsyz, a, m, 0);
 }
References mult_by_term().
Referenced by GBinhom_comp::compute_s_pair(), GB_comp::compute_s_pair(), gb2_comp::compute_s_pair(), gbB::compute_s_pair(), gbA::compute_s_pair(), gbB::spair_set_lead_spoly(), and gbA::spair_set_lead_spoly().