Macaulay2 Engine: GBRing::gbvector_copy
gbvector_copy()
gbvector * GBRing::gbvector_copy (const gbvector * f)
Definition at line 573 of file gbring.cpp.
 {
   gbvector head;
   gbvector *b = &head;
   for (; f != 0; f = f->next, b = b->next) b->next = gbvector_copy_term(f);
   b->next = 0;
   return head.next;
 }
References gbvector_copy_term(), and gbvector::next.
Referenced by MarkedGB::add_marked_elems(), GBKernelComputation::calc(), gbvectorHeap::current_value(), gbA::gbelem_copy(), ReducedGB_Field::minimalize(), ReducedGB_ZZ::minimalize(), ReducedGB_Field_Local::minimalize(), gbA::reduce_kk(), gbA::reduce_ZZ(), gbB::reduceit(), and ReducedGB_Field_Local::store_in_table().