Macaulay2 Engine: getElement< M2::ARingGFGivaro >
getElement< M2::ARingGFGivaro >()
template<> void getElement< M2::ARingGFGivaro > (const M2::ARingGFGivaro & R, int index, M2::ARingGFGivaro::ElementType & result)
Definition at line 48 of file ARingGFTest.cpp.
 {
   M2::ARingGFGivaro::ElementType gen;
   R.init(gen);
   R.getGenerator(gen);
   if (index >= nelements)
     R.power(result, gen, rawRandomInt(static_cast<int32_t>(R.cardinality())));
   else
     R.power(result, gen, randomVals[index]);
   R.clear(gen);
 }
References Ring::getGenerator(), nelements, Ring::power(), RingElement::R, randomVals, and rawRandomInt().