Macaulay2 Engine: rawARingGFPolynomial
rawARingGFPolynomial()
M2_arrayintOrNull rawARingGFPolynomial (const Ring * R)
Definition at line 252 of file aring.cpp.
 {
 #if 1
   const M2::ConcreteRing<M2::ARingGFGivaro> *RGF =
       dynamic_cast<const M2::ConcreteRing<M2::ARingGFGivaro> *>(R);
   if (RGF == 0)
     {
       ERROR("expected a GaloisField");
       return 0;
     }
   const M2::ARingGFGivaro &A = RGF->ring();
   return A.getModPolynomialCoeffs();
 #else
   ERROR("add --enable-fflas-ffpack --enable-givaro when building M2");
   return 0;
 #endif
 }
References ERROR(), M2::ARingGFGivaro::getModPolynomialCoeffs(), and M2::ConcreteRing< RingType >::ring().