Macaulay2 Engine: rawARingGaloisFieldFromQuotient
rawARingGaloisFieldFromQuotient()
const Ring* rawARingGaloisFieldFromQuotient (const RingElement * prim)
Definition at line 194 of file aring.cpp.
 {
   // Check that the ring R of f is a polynomial ring in one var over a ZZ/p
   // Check that f has degree >= 2
   // Check that f is monic
   // If any of these fail, then return 0.
   const PolynomialRing *R = a->get_ring()->cast_to_PolynomialRing();
   if (R == 0)
     {
       ERROR("expected poly ring of the form ZZ/p[x]/(f)");
       return 0;
     }
   if (R->n_vars() != 1)
     {
       ERROR("expected poly ring of the form ZZ/p[x]/(f)");
       return 0;
     }
   if (R->n_quotients() != 1)
     {
       ERROR("expected poly ring of the form ZZ/p[x]/(f)");
       return 0;
     }
   if (R->characteristic() == 0)
     {
       ERROR("expected poly ring of the form ZZ/p[x]/(f)");
       return 0;
     }
   if (!R->is_equal(a->get_value(), R->var(0)))
     {
       ERROR(
           "primitive element needs to be the generator of the ring, we "
           "think...!");
       return 0;
     }
   try
     {
       RingElement F(R, R->quotient_element(0));
       M2_arrayint modPoly = F.getSmallIntegerCoefficients();
       if (modPoly == 0)
         {
           ERROR("internal error: this should not happen");
           return NULL;
         }
       M2_arrayint primitiveElementPoly = a->getSmallIntegerCoefficients();
       if (primitiveElementPoly == 0) return NULL;
       M2::ARingGFGivaro *A = new M2::ARingGFGivaro(
           R->characteristic(), modPoly, primitiveElementPoly, *R);
       return M2::ConcreteRing<M2::ARingGFGivaro>::create(A);
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return NULL;
   }
 }
References Ring::cast_to_PolynomialRing(), Ring::characteristic(), M2::ConcreteRing< RingType >::create(), ERROR(), RingElement::get_ring(), RingElement::get_value(), RingElement::getSmallIntegerCoefficients(), Ring::is_equal(), PolynomialRing::n_quotients(), PolynomialRing::n_vars(), PolynomialRing::quotient_element(), and PolynomialRing::var().