version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/M2/Macaulay2/editors/prism"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/M2/Macaulay2/editors/highlightjs"
    schedule:
      interval: "weekly"
