var hierarchy =
[
    [ "std::allocator< T >", null, null ],
    [ "AllocLogger", "d4/d6d/class_alloc_logger.html", null ],
    [ "ARing", "d1/d7e/class_a_ring.html", [
      [ "M2::AConcreteRing< RingType >", "d3/dd1/class_m2_1_1_a_concrete_ring.html", null ]
    ] ],
    [ "ARingElem< RT >", "d9/d09/class_a_ring_elem.html", null ],
    [ "ARingElement< RT >", "d9/d84/class_a_ring_element.html", null ],
    [ "ARingElementGenerator< RingType >", "df/dc2/class_a_ring_element_generator.html", null ],
    [ "M2::ARingPolynomialStruct", "db/d05/struct_m2_1_1_a_ring_polynomial_struct.html", null ],
    [ "std::array< T >", null, null ],
    [ "AssociatedPrimes", "d5/dc8/class_associated_primes.html", null ],
    [ "std::atomic< T >", null, null ],
    [ "std::atomic_ref< T >", null, null ],
    [ "std::auto_ptr< T >", null, null ],
    [ "std::basic_string< Char >", null, [
      [ "std::string", null, null ],
      [ "std::u16string", null, null ],
      [ "std::u32string", null, null ],
      [ "std::u8string", null, null ],
      [ "std::wstring", null, null ]
    ] ],
    [ "std::basic_string< char >", null, null ],
    [ "std::basic_string< char16_t >", null, null ],
    [ "std::basic_string< char32_t >", null, null ],
    [ "std::basic_string< char8_t >", null, null ],
    [ "std::basic_string< wchar_t >", null, null ],
    [ "std::basic_string_view< Char >", null, [
      [ "std::string_view", null, null ],
      [ "std::u16string_view", null, null ],
      [ "std::u32string_view", null, null ],
      [ "std::u8string_view", null, null ],
      [ "std::wstring_view", null, null ]
    ] ],
    [ "std::basic_string_view< char >", null, null ],
    [ "std::basic_string_view< char16_t >", null, null ],
    [ "std::basic_string_view< char32_t >", null, null ],
    [ "std::basic_string_view< char8_t >", null, null ],
    [ "std::basic_string_view< wchar_t >", null, null ],
    [ "BettiDisplay", "d6/d45/class_betti_display.html", null ],
    [ "BettiHashAndEq", "d7/d37/class_betti_hash_and_eq.html", null ],
    [ "binary_function", null, [
      [ "MarkedGB_sorter", "d4/d5b/struct_marked_g_b__sorter.html", null ],
      [ "montable_sorter_ZZ", "d9/d6a/structmontable__sorter___z_z.html", null ],
      [ "ReducedGB_Field_Local_sorter", "da/da4/struct_reduced_g_b___field___local__sorter.html", null ],
      [ "ReducedGB_Field_sorter", "db/dd8/struct_reduced_g_b___field__sorter.html", null ],
      [ "ReducedGB_ZZ_sorter", "d8/d0a/struct_reduced_g_b___z_z__sorter.html", null ],
      [ "sorter", "df/d8a/structsorter.html", null ]
    ] ],
    [ "Table_T::binding", "db/d77/struct_table___t_1_1binding.html", null ],
    [ "std::bitset< Bits >", null, null ],
    [ "BIBasis::BooleanInvolutiveBasis< MonomType >", "d7/d7e/class_b_i_basis_1_1_boolean_involutive_basis.html", null ],
    [ "BRP", "db/d1b/class_b_r_p.html", null ],
    [ "Callback", null, [
      [ "MGBCallback", "df/df8/class_m_g_b_callback.html", null ]
    ] ],
    [ "cc_doubles_struct", "db/dae/structcc__doubles__struct.html", null ],
    [ "cc_struct", "de/d31/structcc__struct.html", null ],
    [ "CC_struct", "d3/d66/struct_c_c__struct.html", null ],
    [ "CCmutable_struct", "d6/ddb/struct_c_cmutable__struct.html", null ],
    [ "ChineseRemainder", "d0/d4e/class_chinese_remainder.html", null ],
    [ "CoefficientRingType", "db/dc3/struct_coefficient_ring_type.html", null ],
    [ "CoefficientVector", "d8/da3/class_coefficient_vector.html", null ],
    [ "NCF4::Column", "d8/dcb/struct_n_c_f4_1_1_column.html", null ],
    [ "Matrix::column_iterator", "de/dfe/class_matrix_1_1column__iterator.html", null ],
    [ "ColumnsSorter", "d9/d05/class_columns_sorter.html", null ],
    [ "std::complex", null, null ],
    [ "complex", "d6/d3b/classcomplex.html", null ],
    [ "ComplexField", "d5/d7d/class_complex_field.html", null ],
    [ "ConcreteVectorArithmetic< RingType, ElementArrayType >", "d7/d23/class_concrete_vector_arithmetic.html", null ],
    [ "std::wstring::const_iterator", null, null ],
    [ "std::map< K, T >::const_iterator", null, null ],
    [ "std::unordered_map< K, T >::const_iterator", null, null ],
    [ "Polynomial< CoefficientRingType >::const_iterator", "d3/d58/class_polynomial_1_1const__iterator.html", null ],
    [ "std::u8string::const_iterator", null, null ],
    [ "std::multimap< K, T >::const_iterator", null, null ],
    [ "std::u16string::const_iterator", null, null ],
    [ "std::unordered_multimap< K, T >::const_iterator", null, null ],
    [ "std::set< K >::const_iterator", null, null ],
    [ "std::unordered_set< K >::const_iterator", null, null ],
    [ "std::multiset< K >::const_iterator", null, null ],
    [ "std::unordered_multiset< K >::const_iterator", null, null ],
    [ "std::u32string::const_iterator", null, null ],
    [ "std::basic_string_view< Char >::const_iterator", null, null ],
    [ "std::array< T >::const_iterator", null, null ],
    [ "std::vector< T >::const_iterator", null, null ],
    [ "std::span< T >::const_iterator", null, null ],
    [ "std::string_view::const_iterator", null, null ],
    [ "std::wstring_view::const_iterator", null, null ],
    [ "std::u8string_view::const_iterator", null, null ],
    [ "std::u16string_view::const_iterator", null, null ],
    [ "std::basic_string< Char >::const_iterator", null, null ],
    [ "std::u32string_view::const_iterator", null, null ],
    [ "std::deque< T >::const_iterator", null, null ],
    [ "std::list< T >::const_iterator", null, null ],
    [ "std::string::const_iterator", null, null ],
    [ "std::forward_list< T >::const_iterator", null, null ],
    [ "std::forward_list< T >::const_reverse_iterator", null, null ],
    [ "std::wstring::const_reverse_iterator", null, null ],
    [ "std::map< K, T >::const_reverse_iterator", null, null ],
    [ "std::unordered_map< K, T >::const_reverse_iterator", null, null ],
    [ "std::u8string::const_reverse_iterator", null, null ],
    [ "std::multimap< K, T >::const_reverse_iterator", null, null ],
    [ "std::unordered_multimap< K, T >::const_reverse_iterator", null, null ],
    [ "std::u16string::const_reverse_iterator", null, null ],
    [ "std::set< K >::const_reverse_iterator", null, null ],
    [ "std::unordered_set< K >::const_reverse_iterator", null, null ],
    [ "std::u32string::const_reverse_iterator", null, null ],
    [ "std::multiset< K >::const_reverse_iterator", null, null ],
    [ "std::unordered_multiset< K >::const_reverse_iterator", null, null ],
    [ "std::basic_string_view< Char >::const_reverse_iterator", null, null ],
    [ "std::array< T >::const_reverse_iterator", null, null ],
    [ "std::vector< T >::const_reverse_iterator", null, null ],
    [ "std::span< T >::const_reverse_iterator", null, null ],
    [ "std::string_view::const_reverse_iterator", null, null ],
    [ "std::wstring_view::const_reverse_iterator", null, null ],
    [ "std::u8string_view::const_reverse_iterator", null, null ],
    [ "std::u16string_view::const_reverse_iterator", null, null ],
    [ "std::basic_string< Char >::const_reverse_iterator", null, null ],
    [ "std::u32string_view::const_reverse_iterator", null, null ],
    [ "std::deque< T >::const_reverse_iterator", null, null ],
    [ "std::string::const_reverse_iterator", null, null ],
    [ "std::list< T >::const_reverse_iterator", null, null ],
    [ "BIBasis::JanetTree< MonomType >::ConstIterator", "df/da9/class_b_i_basis_1_1_janet_tree_1_1_const_iterator.html", null ],
    [ "ConstZipIterator< U, T >", "da/dfd/class_const_zip_iterator.html", null ],
    [ "DegreeZeroMapGenerator", "de/df3/class_degree_zero_map_generator.html", null ],
    [ "std::deque< T >", null, null ],
    [ "std::deque< Overlap >", null, null ],
    [ "ReducedGB_Field_Local::divisor_info", "db/dae/struct_reduced_g_b___field___local_1_1divisor__info.html", null ],
    [ "DMat< ACoeffRing >", "da/dc3/class_d_mat.html", null ],
    [ "DMat< M2::ARingGFFlint >", "d3/d1d/class_d_mat_3_01_m2_1_1_a_ring_g_f_flint_01_4.html", null ],
    [ "DMat< M2::ARingGFFlintBig >", "d1/dbb/class_d_mat_3_01_m2_1_1_a_ring_g_f_flint_big_01_4.html", null ],
    [ "DMat< M2::ARingQQFlint >", "d6/de7/class_d_mat_3_01_m2_1_1_a_ring_q_q_flint_01_4.html", null ],
    [ "DMat< M2::ARingZZ >", "d2/da8/class_d_mat_3_01_m2_1_1_a_ring_z_z_01_4.html", null ],
    [ "DMat< M2::ARingZZpFlint >", "d6/d70/class_d_mat_3_01_m2_1_1_a_ring_z_zp_flint_01_4.html", null ],
    [ "DMat< RingType >", "da/dc3/class_d_mat.html", null ],
    [ "DMatConstIterator< ACoeffRing >", "d6/d9a/class_d_mat_const_iterator.html", null ],
    [ "DMatIterator< ACoeffRing >", "df/d28/class_d_mat_iterator.html", null ],
    [ "DMatLinAlg< RingType >", "d8/df6/class_d_mat_lin_alg.html", null ],
    [ "DMatLinAlg< M2::ARingQQ >", "d7/d2b/class_d_mat_lin_alg_3_01_m2_1_1_a_ring_q_q_01_4.html", null ],
    [ "DMatLinAlg< M2::ARingZZpFFPACK >", "dc/d87/class_d_mat_lin_alg_3_01_m2_1_1_a_ring_z_zp_f_f_p_a_c_k_01_4.html", null ],
    [ "DMatLinAlg< M2::ARingZZpFlint >", "d1/d10/class_d_mat_lin_alg_3_01_m2_1_1_a_ring_z_zp_flint_01_4.html", null ],
    [ "DMatLUinPlace< RT >", "df/d1c/class_d_mat_l_uin_place.html", null ],
    [ "DMatLUinPlace< RingType >", "df/d1c/class_d_mat_l_uin_place.html", null ],
    [ "DPoly", "d3/d42/class_d_poly.html", null ],
    [ "EigenTypes< RT >", "da/dfe/struct_eigen_types.html", null ],
    [ "EigenTypes< M2::ARingCC >", "dd/dfb/struct_eigen_types_3_01_m2_1_1_a_ring_c_c_01_4.html", null ],
    [ "EigenTypes< M2::ARingCCC >", "de/d33/struct_eigen_types_3_01_m2_1_1_a_ring_c_c_c_01_4.html", null ],
    [ "EigenTypes< M2::ARingRR >", "d9/dc6/struct_eigen_types_3_01_m2_1_1_a_ring_r_r_01_4.html", null ],
    [ "EigenTypes< M2::ARingRRR >", "dd/dbb/struct_eigen_types_3_01_m2_1_1_a_ring_r_r_r_01_4.html", null ],
    [ "ElementArray", "d5/d94/class_element_array.html", null ],
    [ "enter_factory", "db/d86/structenter__factory.html", null ],
    [ "EntryConfig", "d4/de5/class_entry_config.html", null ],
    [ "std::error_category", null, null ],
    [ "std::error_code", null, null ],
    [ "std::error_condition", null, null ],
    [ "std::exception", null, [
      [ "mpfr::conversion_overflow", "d3/d03/classmpfr_1_1conversion__overflow.html", null ],
      [ "std::bad_alloc", null, null ],
      [ "std::bad_cast", null, null ],
      [ "std::bad_exception", null, null ],
      [ "std::bad_typeid", null, null ],
      [ "std::ios_base::failure", null, null ],
      [ "std::logic_error", null, [
        [ "std::domain_error", null, null ],
        [ "std::invalid_argument", null, null ],
        [ "std::length_error", null, null ],
        [ "std::out_of_range", null, null ]
      ] ],
      [ "std::runtime_error", null, [
        [ "exc::engine_error", "da/dbb/structexc_1_1engine__error.html", [
          [ "exc::division_by_zero_error", "d1/daf/structexc_1_1division__by__zero__error.html", null ],
          [ "exc::internal_error", "d1/d91/structexc_1_1internal__error.html", null ],
          [ "exc::overflow_exception", "db/df5/structexc_1_1overflow__exception.html", null ]
        ] ],
        [ "std::overflow_error", null, null ],
        [ "std::range_error", null, null ],
        [ "std::underflow_error", null, null ]
      ] ]
    ] ],
    [ "exponent_table", "d7/db5/structexponent__table.html", null ],
    [ "F4Res", "d0/dd7/class_f4_res.html", null ],
    [ "F4toM2Interface", "d5/df9/class_f4to_m2_interface.html", null ],
    [ "F4Vec", "df/de1/class_f4_vec.html", null ],
    [ "BIBasis::FastAllocator", "d1/df2/class_b_i_basis_1_1_fast_allocator.html", null ],
    [ "FF_LUComputation", "d7/db4/class_f_f___l_u_computation.html", null ],
    [ "ResGausserQQHybrid::FieldElement", "da/db7/struct_res_gausser_q_q_hybrid_1_1_field_element.html", null ],
    [ "ResGausserQQ::FieldElement", "de/d99/struct_res_gausser_q_q_1_1_field_element.html", null ],
    [ "FixedPrecisionHomotopyAlgorithm", "d9/ddd/class_fixed_precision_homotopy_algorithm.html", null ],
    [ "FlintQQMat", "d2/d11/class_flint_q_q_mat.html", null ],
    [ "FlintZZMat", "d9/d3a/class_flint_z_z_mat.html", null ],
    [ "std::forward_list< T >", null, null ],
    [ "frac_elem", "d6/d62/structfrac__elem.html", null ],
    [ "SchreyerFrame::Frame", "d7/df5/struct_schreyer_frame_1_1_frame.html", null ],
    [ "SchreyerFrameTypes::FrameElement", "d8/df1/struct_schreyer_frame_types_1_1_frame_element.html", null ],
    [ "FreeAlgebraElement", "dc/d2e/class_free_algebra_element.html", null ],
    [ "FreeAlgebraHeap", "d4/d31/class_free_algebra_heap.html", null ],
    [ "FreeAlgebraQuotientElement", "d2/d58/class_free_algebra_quotient_element.html", null ],
    [ "FreeModule_symm", "da/d99/struct_free_module__symm.html", null ],
    [ "FreeMonoidLogger", "d0/dc7/class_free_monoid_logger.html", null ],
    [ "FunctionPair", "d2/d44/class_function_pair.html", null ],
    [ "M2::GaloisFieldTable", "d5/dab/class_m2_1_1_galois_field_table.html", null ],
    [ "gbA::gbelem", "d7/dce/structgb_a_1_1gbelem.html", null ],
    [ "gbB::gbelem", "d5/df7/structgb_b_1_1gbelem.html", null ],
    [ "GBList", "d3/db8/class_g_b_list.html", null ],
    [ "GBTracer", "d0/d0e/class_g_b_tracer.html", null ],
    [ "gbvector", "d7/d40/structgbvector.html", null ],
    [ "gbvectorHeap", "dc/d58/classgbvector_heap.html", null ],
    [ "geobucket< FREEMODULETYPE, VECTYPE >", "d5/d03/classgeobucket.html", null ],
    [ "HilbertController", "dd/dc6/class_hilbert_controller.html", null ],
    [ "HomotopyAlgorithm< RT >", "d6/d19/struct_homotopy_algorithm.html", null ],
    [ "HomotopyAlgorithm< M2::ARingCC >", "dd/d40/struct_homotopy_algorithm_3_01_m2_1_1_a_ring_c_c_01_4.html", null ],
    [ "HomotopyAlgorithm< M2::ARingCCC >", "d4/ddf/struct_homotopy_algorithm_3_01_m2_1_1_a_ring_c_c_c_01_4.html", null ],
    [ "IdealConsumer", null, [
      [ "MyIdealConsumer", "d8/d5c/class_my_ideal_consumer.html", null ]
    ] ],
    [ "indent", "d2/dd2/structindent.html", null ],
    [ "Index< T >", "d3/de8/class_index.html", null ],
    [ "index_res_varpower_monomial", "d9/d3c/classindex__res__varpower__monomial.html", null ],
    [ "index_varpower", "d4/ded/classindex__varpower.html", null ],
    [ "index_varpower_monomial", "d4/d60/classindex__varpower__monomial.html", null ],
    [ "intarray", "d3/d23/classintarray.html", null ],
    [ "Interreducer", "d5/d51/class_interreducer.html", null ],
    [ "IntsSet< Configuration >", "dc/dd8/class_ints_set.html", null ],
    [ "std::ios_base", null, [
      [ "std::basic_ios< char >", null, null ],
      [ "std::basic_ios< wchar_t >", null, null ],
      [ "std::basic_ios< Char >", null, [
        [ "std::basic_istream< char >", null, null ],
        [ "std::basic_istream< wchar_t >", null, null ],
        [ "std::basic_ostream< char >", null, null ],
        [ "std::basic_ostream< wchar_t >", null, null ],
        [ "std::basic_istream< Char >", null, [
          [ "std::basic_ifstream< char >", null, null ],
          [ "std::basic_ifstream< wchar_t >", null, null ],
          [ "std::basic_iostream< char >", null, null ],
          [ "std::basic_iostream< wchar_t >", null, null ],
          [ "std::basic_istringstream< char >", null, null ],
          [ "std::basic_istringstream< wchar_t >", null, null ],
          [ "std::basic_ifstream< Char >", null, [
            [ "std::ifstream", null, null ],
            [ "std::wifstream", null, null ]
          ] ],
          [ "std::basic_iostream< Char >", null, [
            [ "std::basic_fstream< char >", null, null ],
            [ "std::basic_fstream< wchar_t >", null, null ],
            [ "std::basic_stringstream< char >", null, null ],
            [ "std::basic_stringstream< wchar_t >", null, null ],
            [ "std::basic_fstream< Char >", null, [
              [ "std::fstream", null, null ],
              [ "std::wfstream", null, null ]
            ] ],
            [ "std::basic_stringstream< Char >", null, [
              [ "std::stringstream", null, null ],
              [ "std::wstringstream", null, null ]
            ] ]
          ] ],
          [ "std::basic_istringstream< Char >", null, [
            [ "std::istringstream", null, null ],
            [ "std::wistringstream", null, null ]
          ] ],
          [ "std::istream", null, null ],
          [ "std::wistream", null, null ]
        ] ],
        [ "std::basic_ostream< Char >", null, [
          [ "std::basic_iostream< char >", null, null ],
          [ "std::basic_iostream< wchar_t >", null, null ],
          [ "std::basic_ofstream< char >", null, null ],
          [ "std::basic_ofstream< wchar_t >", null, null ],
          [ "std::basic_ostringstream< char >", null, null ],
          [ "std::basic_ostringstream< wchar_t >", null, null ],
          [ "std::basic_iostream< Char >", null, null ],
          [ "std::basic_ofstream< Char >", null, [
            [ "std::ofstream", null, null ],
            [ "std::wofstream", null, null ]
          ] ],
          [ "std::basic_ostringstream< Char >", null, [
            [ "std::ostringstream", null, null ],
            [ "std::wostringstream", null, null ]
          ] ],
          [ "std::ostream", null, null ],
          [ "std::wostream", null, null ]
        ] ],
        [ "std::ios", null, null ],
        [ "std::wios", null, null ]
      ] ]
    ] ],
    [ "std::wstring::iterator", null, null ],
    [ "std::map< K, T >::iterator", null, null ],
    [ "std::u8string::iterator", null, null ],
    [ "std::unordered_map< K, T >::iterator", null, null ],
    [ "std::multimap< K, T >::iterator", null, null ],
    [ "std::unordered_multimap< K, T >::iterator", null, null ],
    [ "std::u16string::iterator", null, null ],
    [ "std::set< K >::iterator", null, null ],
    [ "DegreeZeroMapGenerator::iterator", "d1/d71/class_degree_zero_map_generator_1_1iterator.html", null ],
    [ "std::u32string::iterator", null, null ],
    [ "std::unordered_set< K >::iterator", null, null ],
    [ "std::multiset< K >::iterator", null, null ],
    [ "std::unordered_multiset< K >::iterator", null, null ],
    [ "std::basic_string_view< Char >::iterator", null, null ],
    [ "std::array< T >::iterator", null, null ],
    [ "std::vector< T >::iterator", null, null ],
    [ "std::span< T >::iterator", null, null ],
    [ "std::string_view::iterator", null, null ],
    [ "binomialGB::iterator", "d7/dbd/classbinomial_g_b_1_1iterator.html", null ],
    [ "std::wstring_view::iterator", null, null ],
    [ "std::u8string_view::iterator", null, null ],
    [ "std::u16string_view::iterator", null, null ],
    [ "std::basic_string< Char >::iterator", null, null ],
    [ "std::u32string_view::iterator", null, null ],
    [ "std::deque< T >::iterator", null, null ],
    [ "std::string::iterator", null, null ],
    [ "BIBasis::JanetTree< MonomType >::Iterator", "d3/d61/class_b_i_basis_1_1_janet_tree_1_1_iterator.html", null ],
    [ "std::list< T >::iterator", null, null ],
    [ "MutableComplex::iterator", "d0/d4f/class_mutable_complex_1_1iterator.html", null ],
    [ "std::forward_list< T >::iterator", null, null ],
    [ "BIBasis::JanetTree< MonomType >", "d2/d19/class_b_i_basis_1_1_janet_tree.html", null ],
    [ "std::jthread", null, null ],
    [ "KBasis", "d9/dd1/class_k_basis.html", null ],
    [ "Lapack", "df/dd6/class_lapack.html", null ],
    [ "BIBasis::Launcher", "d7/d07/class_b_i_basis_1_1_launcher.html", null ],
    [ "SchreyerFrame::Level", "da/d4d/struct_schreyer_frame_1_1_level.html", null ],
    [ "lex", "d2/dfa/structlex.html", null ],
    [ "std::list< T >", null, null ],
    [ "std::list< BIBasis::Polynom< MonomType > * >", null, null ],
    [ "std::list< BIBasis::Triple< MonomType > * >", null, null ],
    [ "std::list< brMonomial >", null, null ],
    [ "LLLoperations", "d8/d7d/class_l_l_loperations.html", null ],
    [ "local_elem", "d4/d20/structlocal__elem.html", null ],
    [ "std::lock_guard< T >", null, null ],
    [ "LUUtil< RT >", "df/dcd/class_l_u_util.html", null ],
    [ "std::map< K, T >", null, null ],
    [ "std::map< Label, SuffixTreeNode * >", null, null ],
    [ "std::map< Monom, ring_elem, MonomEq, gc_allocator< ConstEntry > >", null, null ],
    [ "std::map< std::pair< int, bool >, std::deque< Overlap > >", null, null ],
    [ "std::map< Weight, int >", null, null ],
    [ "MatElementaryOps< MT >", "db/d2e/class_mat_elementary_ops.html", null ],
    [ "MatElementaryOps< DMat< RT > >", "d1/ddf/class_mat_elementary_ops_3_01_d_mat_3_01_r_t_01_4_01_4.html", null ],
    [ "MatElementaryOps< SMat< RT > >", "d3/db3/class_mat_elementary_ops_3_01_s_mat_3_01_r_t_01_4_01_4.html", null ],
    [ "MatrixConstructor", "d3/d7a/class_matrix_constructor.html", null ],
    [ "MatrixSorter", "da/d1d/class_matrix_sorter.html", null ],
    [ "MatrixStream", "d6/d02/class_matrix_stream.html", null ],
    [ "MatrixWindow", "df/d6c/struct_matrix_window.html", null ],
    [ "MemoryBlock< T, NSLAB >", "d3/d57/class_memory_block.html", null ],
    [ "MemoryBlock< res_monomial_word >", "d3/d57/class_memory_block.html", null ],
    [ "MemoryBlock< res_varpower_word >", "d3/d57/class_memory_block.html", null ],
    [ "MemoryBlock< SchreyerFrameTypes::PreElement >", "d3/d57/class_memory_block.html", null ],
    [ "MinimalPrimes", "db/d26/class_minimal_primes.html", null ],
    [ "mo_block", "dd/dbb/structmo__block.html", null ],
    [ "ModuleMonom", "d9/d8a/class_module_monom.html", null ],
    [ "ModuleMonomDefaultConfig", "d0/df9/class_module_monom_default_config.html", null ],
    [ "ModuleMonomDefaultConfigOrig", "dd/d04/class_module_monom_default_config_orig.html", null ],
    [ "ModuleMonomEq", "d7/dd4/class_module_monom_eq.html", null ],
    [ "ModuleMonomHash", "d7/df6/class_module_monom_hash.html", null ],
    [ "ModuleMonomLessThan", "db/dd2/class_module_monom_less_than.html", null ],
    [ "mon_part", "d3/de9/structmon__part__rec__.html", null ],
    [ "MonomialTable::mon_term", "d7/d75/struct_monomial_table_1_1mon__term.html", null ],
    [ "Monom", "dd/d21/struct_monom.html", null ],
    [ "BIBasis::Monom", "d4/d58/class_b_i_basis_1_1_monom.html", [
      [ "BIBasis::MonomDL", "dd/d51/class_b_i_basis_1_1_monom_d_l.html", null ],
      [ "BIBasis::MonomDRL", "d0/da6/class_b_i_basis_1_1_monom_d_r_l.html", null ],
      [ "BIBasis::MonomLex", "d7/dc5/class_b_i_basis_1_1_monom_lex.html", null ]
    ] ],
    [ "monom_int_list", "d4/d08/classmonom__int__list.html", null ],
    [ "MonomEq", "d7/d79/class_monom_eq.html", null ],
    [ "MonomHash", "d0/da5/class_monom_hash.html", null ],
    [ "MonomHashEqual", "dc/dd6/class_monom_hash_equal.html", null ],
    [ "MonomialCollectionFixedSize", "d6/dd5/class_monomial_collection_fixed_size.html", null ],
    [ "MonomialCollectionVarSize", "d4/d7c/class_monomial_collection_var_size.html", null ],
    [ "MonomialHashAndEqFixedSize", "d8/da4/class_monomial_hash_and_eq_fixed_size.html", null ],
    [ "MonomialHashAndEqVarSize", "d2/d70/class_monomial_hash_and_eq_var_size.html", null ],
    [ "MonomialHashTable< ValueType >", "d0/d1f/class_monomial_hash_table.html", null ],
    [ "MonomialHashTable< MonomialInfo >", "d0/d1f/class_monomial_hash_table.html", null ],
    [ "MonomialHashTable< ResMonomialsWithComponent >", "d0/d1f/class_monomial_hash_table.html", null ],
    [ "MonomialMemorySpace", "d3/d43/class_monomial_memory_space.html", null ],
    [ "MonomialOrder", "d0/d87/struct_monomial_order__rec.html", null ],
    [ "MonomialOrdering", "dd/d53/struct_monomial_ordering.html", null ],
    [ "MonomialOrderings", "d7/d7c/class_monomial_orderings.html", null ],
    [ "MonomialOrderMatrix", "d5/d82/class_monomial_order_matrix.html", null ],
    [ "MonomialSetFixedSize", "d4/d11/class_monomial_set_fixed_size.html", null ],
    [ "MonomialSetVarSize", "da/d9e/class_monomial_set_var_size.html", null ],
    [ "MonomialsIgnoringComponent", "da/d64/class_monomials_ignoring_component.html", null ],
    [ "MonomialSorterObject", "dd/d94/class_monomial_sorter_object.html", null ],
    [ "MonomialsWithComponent", "d9/db6/class_monomials_with_component.html", null ],
    [ "MonomSort< T >", "de/dff/struct_monom_sort.html", null ],
    [ "mpfr::mpreal", "d6/df7/classmpfr_1_1mpreal.html", null ],
    [ "std::multimap< K, T >", null, null ],
    [ "std::multiset< K >", null, null ],
    [ "MutableMat< Mat >", "d6/db0/class_mutable_mat.html", null ],
    [ "std::mutex", null, null ],
    [ "NaiveDedupQueueConfiguration", "dd/dc4/class_naive_dedup_queue_configuration.html", null ],
    [ "NaiveQueueConfiguration", "d0/d65/class_naive_queue_configuration.html", null ],
    [ "NCF4::NCF4Stats", "d8/df0/struct_n_c_f4_1_1_n_c_f4_stats.html", null ],
    [ "newdelete", "d8/d71/classnewdelete.html", [
      [ "GBTrace", "d5/d73/class_g_b_trace.html", null ]
    ] ],
    [ "GBTrace::node", "d0/da6/struct_g_b_trace_1_1node.html", null ],
    [ "BIBasis::JanetTree< MonomType >::Node", "df/da3/struct_b_i_basis_1_1_janet_tree_1_1_node.html", null ],
    [ "Nterm", "d0/dbc/struct_nterm.html", null ],
    [ "ntuple", "da/dc4/classntuple.html", null ],
    [ "ntuple_monomials", "df/d8a/classntuple__monomials.html", null ],
    [ "std::numeric_limits< mpfr::mpreal >", "d6/dba/classstd_1_1numeric__limits_3_01mpfr_1_1mpreal_01_4.html", null ],
    [ "our_new_delete", "da/dcc/structour__new__delete.html", [
      [ "auto_reduce_node", "d6/dd2/structauto__reduce__node.html", null ],
      [ "binomial", "de/df1/structbinomial.html", null ],
      [ "binomial_gb_elem", "d7/d61/structbinomial__gb__elem.html", null ],
      [ "binomial_ring", "dd/d3a/classbinomial__ring.html", null ],
      [ "binomial_s_pair", "de/d61/structbinomial__s__pair.html", null ],
      [ "binomial_s_pair_set", "d1/d7e/classbinomial__s__pair__set.html", null ],
      [ "binomial_s_pair_set::s_pair_degree_list", "d2/d2f/structbinomial__s__pair__set_1_1s__pair__degree__list.html", null ],
      [ "binomial_s_pair_set::s_pair_elem", "d8/db2/structbinomial__s__pair__set_1_1s__pair__elem.html", null ],
      [ "binomial_s_pair_set::s_pair_lcm_list", "d0/d2a/structbinomial__s__pair__set_1_1s__pair__lcm__list.html", null ],
      [ "binomialGB", "d6/d05/classbinomial_g_b.html", null ],
      [ "binomialGB::gbmin_elem", "db/dee/structbinomial_g_b_1_1gbmin__elem.html", null ],
      [ "binomialGB::monomial_list", "d6/d0d/structbinomial_g_b_1_1monomial__list.html", null ],
      [ "buffer", "da/d40/classbuffer.html", null ],
      [ "coefficient_matrix", "d8/dce/structcoefficient__matrix.html", null ],
      [ "CoefficientRingR", "d1/d34/class_coefficient_ring_r.html", null ],
      [ "CoefficientRingZZp", "dd/dd5/class_coefficient_ring_z_zp.html", null ],
      [ "column_elem", "d3/d69/structcolumn__elem.html", null ],
      [ "dense_row", "df/d8a/structdense__row.html", null ],
      [ "DetComputation", "d7/d9a/class_det_computation.html", null ],
      [ "doubling_stash", "da/d01/classdoubling__stash.html", null ],
      [ "DPolyTraverser", "d4/d61/class_d_poly_traverser.html", [
        [ "TowerEvaluator", "dc/d52/class_tower_evaluator.html", null ]
      ] ],
      [ "DRing", "d6/de6/class_d_ring.html", null ],
      [ "EngineObject", "d4/d3f/class_engine_object.html", [
        [ "FreeModule", "d6/df0/class_free_module.html", null ],
        [ "Matrix", "d6/d3f/class_matrix.html", null ],
        [ "Monomial", "d4/daa/class_monomial.html", null ],
        [ "MonomialIdeal", "df/ddb/class_monomial_ideal.html", null ],
        [ "RingElement", "d6/de2/class_ring_element.html", null ],
        [ "RingMap", "d6/d6a/class_ring_map.html", null ]
      ] ],
      [ "exc::engine_error", "da/dbb/structexc_1_1engine__error.html", null ],
      [ "F4GB", "d9/d4a/class_f4_g_b.html", null ],
      [ "F4Mem", "d5/d43/class_f4_mem.html", null ],
      [ "F4MemoryBlock< T, NSLAB >", "d8/d75/class_f4_memory_block.html", null ],
      [ "F4MemoryBlock< T, NSLAB >::slab", "d0/dc6/struct_f4_memory_block_1_1slab.html", null ],
      [ "F4MemoryBlock< monomial_word >", "d8/d75/class_f4_memory_block.html", null ],
      [ "F4MemoryBlock< pre_spair >", "d8/d75/class_f4_memory_block.html", null ],
      [ "F4MemoryBlock< varpower_word >", "d8/d75/class_f4_memory_block.html", null ],
      [ "F4MonomialLookupTableT< Key >", "d6/d10/class_f4_monomial_lookup_table_t.html", null ],
      [ "F4MonomialLookupTableT< Key >::mi_node", "d9/dc7/struct_f4_monomial_lookup_table_t_1_1mi__node.html", null ],
      [ "F4SPairSet", "d9/d22/class_f4_s_pair_set.html", null ],
      [ "FreeAlgebra", "de/dbd/class_free_algebra.html", null ],
      [ "FreeAlgebraQuotient", "d0/d77/class_free_algebra_quotient.html", null ],
      [ "FreeMonoid", "dc/da6/class_free_monoid.html", null ],
      [ "Gausser", "d4/db9/class_gausser.html", null ],
      [ "gb_elem", "dc/d9c/structgb__elem.html", null ],
      [ "gb_node", "dc/d99/classgb__node.html", [
        [ "gb2_comp", "dd/df7/classgb2__comp.html", null ],
        [ "gb_emitter", "df/d2c/classgb__emitter.html", null ]
      ] ],
      [ "gbA::SPairSet", "d9/dad/structgb_a_1_1_s_pair_set.html", null ],
      [ "gbB::SPairSet", "d1/ddc/structgb_b_1_1_s_pair_set.html", null ],
      [ "gbelem", "dc/dc0/structgbelem.html", null ],
      [ "GBF4Polynomial", "d5/d39/struct_g_b_f4_polynomial.html", null ],
      [ "GBMatrix", "d7/d14/struct_g_b_matrix.html", null ],
      [ "GBRing", "d8/d73/class_g_b_ring.html", [
        [ "GBRingPoly", "d5/d09/class_g_b_ring_poly.html", null ],
        [ "GBRingSkew", "dd/de7/class_g_b_ring_skew.html", null ],
        [ "GBRingSolvable", "d5/d5c/class_g_b_ring_solvable.html", null ],
        [ "GBRingWeyl", "d3/dd1/class_g_b_ring_weyl.html", [
          [ "GBRingWeylZZ", "d3/d48/class_g_b_ring_weyl_z_z.html", null ]
        ] ]
      ] ],
      [ "GBWeight", "d5/d82/class_g_b_weight.html", null ],
      [ "gm_elem", "d0/dd0/structgm__elem.html", null ],
      [ "hilb_step", "d3/de1/structhilb__step.html", null ],
      [ "hm_elem", "db/dde/structhm__elem.html", null ],
      [ "int_bag", "df/d8c/classint__bag.html", null ],
      [ "M2::RingInterface", "db/d1a/class_m2_1_1_ring_interface.html", [
        [ "M2::ARingCC", "d1/dfa/class_m2_1_1_a_ring_c_c.html", null ],
        [ "M2::ARingCCC", "d6/de1/class_m2_1_1_a_ring_c_c_c.html", null ],
        [ "M2::ARingGFFlint", "d5/d5f/class_m2_1_1_a_ring_g_f_flint.html", null ],
        [ "M2::ARingGFFlintBig", "d8/d7a/class_m2_1_1_a_ring_g_f_flint_big.html", null ],
        [ "M2::ARingGFGivaro", "d6/d8d/class_m2_1_1_a_ring_g_f_givaro.html", null ],
        [ "M2::ARingGFM2", "dd/df1/class_m2_1_1_a_ring_g_f_m2.html", null ],
        [ "M2::ARingQQFlint", "dd/d1b/class_m2_1_1_a_ring_q_q_flint.html", null ],
        [ "M2::ARingQQGMP", "d9/dec/class_m2_1_1_a_ring_q_q_g_m_p.html", null ],
        [ "M2::ARingRR", "d0/d48/class_m2_1_1_a_ring_r_r.html", null ],
        [ "M2::ARingRRi", "dd/d78/class_m2_1_1_a_ring_r_ri.html", null ],
        [ "M2::ARingRRR", "dd/d9e/class_m2_1_1_a_ring_r_r_r.html", null ],
        [ "M2::ARingTower", "da/d48/class_m2_1_1_a_ring_tower.html", null ],
        [ "M2::ARingZZ", "d4/dea/class_m2_1_1_a_ring_z_z.html", null ],
        [ "M2::ARingZZGMP", "db/d2e/class_m2_1_1_a_ring_z_z_g_m_p.html", null ],
        [ "M2::ARingZZp", "d6/d13/class_m2_1_1_a_ring_z_zp.html", null ],
        [ "M2::ARingZZpFFPACK", "da/d73/class_m2_1_1_a_ring_z_zp_f_f_p_a_c_k.html", null ],
        [ "M2::ARingZZpFlint", "d1/d21/class_m2_1_1_a_ring_z_zp_flint.html", null ],
        [ "M2::DummyRing", "d5/d2d/class_m2_1_1_dummy_ring.html", null ]
      ] ],
      [ "Matrix::iterator", "d2/d54/class_matrix_1_1iterator.html", null ],
      [ "monideal_pair", "d7/de9/structmonideal__pair.html", null ],
      [ "MonomialInfo", "dd/dab/class_monomial_info.html", null ],
      [ "MonomialTable", "d9/d3b/class_monomial_table.html", null ],
      [ "MonomialTableZZ", "da/da3/class_monomial_table_z_z.html", null ],
      [ "MonomialTableZZ::mon_term", "dd/d76/struct_monomial_table_z_z_1_1mon__term.html", null ],
      [ "MyIdealConsumer", "d8/d5c/class_my_ideal_consumer.html", null ],
      [ "NCBasis", "d9/d29/class_n_c_basis.html", null ],
      [ "NCF4", "d0/d92/class_n_c_f4.html", null ],
      [ "NCGroebner", "d8/d79/class_n_c_groebner.html", null ],
      [ "Nmi_node", "d0/d1b/class_nmi__node.html", null ],
      [ "our_gc_cleanup", "d3/d31/classour__gc__cleanup.html", [
        [ "MutableEngineObject", "d3/d7b/class_mutable_engine_object.html", [
          [ "Computation", "d6/dea/class_computation.html", [
            [ "GBComputation", "de/ded/class_g_b_computation.html", [
              [ "binomialGB_comp", "da/d1d/classbinomial_g_b__comp.html", null ],
              [ "F4Computation", "d8/d5d/class_f4_computation.html", null ],
              [ "GaussElimComputation", "d3/d16/class_gauss_elim_computation.html", null ],
              [ "GB_comp", "d8/dfa/class_g_b__comp.html", null ],
              [ "gbA", "d0/d91/classgb_a.html", null ],
              [ "gbB", "dd/d1c/classgb_b.html", null ],
              [ "GBDeclared", "d8/d26/class_g_b_declared.html", null ],
              [ "GBinhom_comp", "d6/dfe/class_g_binhom__comp.html", null ],
              [ "GBProxy", "d1/dd3/class_g_b_proxy.html", null ],
              [ "GBWalker", "df/dab/class_g_b_walker.html", null ],
              [ "HermiteComputation", "d8/d76/class_hermite_computation.html", null ],
              [ "ReducedGB", "d9/d3f/class_reduced_g_b.html", [
                [ "MarkedGB", "d2/d89/class_marked_g_b.html", null ],
                [ "ReducedGB_Field", "db/dbc/class_reduced_g_b___field.html", [
                  [ "ReducedGB_Field_Local", "dd/dcb/class_reduced_g_b___field___local.html", null ]
                ] ],
                [ "ReducedGB_ZZ", "d5/ddb/class_reduced_g_b___z_z.html", null ]
              ] ]
            ] ],
            [ "GBKernelComputation", "d7/d37/class_g_b_kernel_computation.html", null ],
            [ "ResolutionComputation", "dd/d51/class_resolution_computation.html", [
              [ "F4ResComputation", "d6/d1e/class_f4_res_computation.html", null ],
              [ "gbres_comp", "d6/dce/classgbres__comp.html", null ],
              [ "NCResComputation", "da/dc1/class_n_c_res_computation.html", null ],
              [ "res2_comp", "db/d31/classres2__comp.html", null ],
              [ "res_comp", "d5/d17/classres__comp.html", null ]
            ] ]
          ] ],
          [ "hilb_comp", "de/dfb/classhilb__comp.html", null ],
          [ "Homotopy", "de/d9d/class_homotopy.html", [
            [ "HomotopyConcrete< RT, Algorithm >", "d9/dc8/class_homotopy_concrete.html", null ],
            [ "HomotopyConcrete< RT, FixedPrecisionHomotopyAlgorithm >", "d2/d78/class_homotopy_concrete_3_01_r_t_00_01_fixed_precision_homotopy_algorithm_01_4.html", null ]
          ] ],
          [ "M2Homotopy", "dc/de6/class_m2_homotopy.html", null ],
          [ "M2PointArray", "d2/dd0/class_m2_point_array.html", null ],
          [ "M2SLEvaluator", "db/d7c/class_m2_s_l_evaluator.html", null ],
          [ "M2SLProgram", "d8/d3a/class_m2_s_l_program.html", null ],
          [ "Monoid", "d9/db1/class_monoid.html", null ],
          [ "MutableComplex", "dc/d43/class_mutable_complex.html", null ],
          [ "MutableMatrix", "dc/db8/class_mutable_matrix.html", null ],
          [ "PathTracker", "de/db9/class_path_tracker.html", null ],
          [ "Ring", "dd/dcf/class_ring.html", [
            [ "M2::ConcreteRing< ARingQQ >", "d0/d99/class_m2_1_1_concrete_ring.html", [
              [ "M2::RingQQ", "d4/d85/class_m2_1_1_ring_q_q.html", null ]
            ] ],
            [ "M2::ConcreteRing< M2::ARingCC >", "d0/d99/class_m2_1_1_concrete_ring.html", null ],
            [ "FractionField", "d6/d42/class_fraction_field.html", null ],
            [ "GF", "d1/d35/class_g_f.html", null ],
            [ "LocalRing", "d6/dfd/class_local_ring.html", null ],
            [ "M2::ConcreteRing< RingType >", "d0/d99/class_m2_1_1_concrete_ring.html", null ],
            [ "M2FreeAlgebraOrQuotient", "de/dd2/class_m2_free_algebra_or_quotient.html", [
              [ "M2FreeAlgebra", "dc/dc0/class_m2_free_algebra.html", null ],
              [ "M2FreeAlgebraQuotient", "db/d22/class_m2_free_algebra_quotient.html", null ]
            ] ],
            [ "PolynomialRing", "d5/d58/class_polynomial_ring.html", [
              [ "PolyRingFlat", "de/dba/class_poly_ring_flat.html", [
                [ "PolyRing", "d3/dfc/class_poly_ring.html", [
                  [ "SchurRing", "dd/ddb/class_schur_ring.html", null ],
                  [ "SkewPolynomialRing", "dc/d98/class_skew_polynomial_ring.html", null ],
                  [ "SolvableAlgebra", "db/daa/class_solvable_algebra.html", null ],
                  [ "WeylAlgebra", "dd/dc2/class_weyl_algebra.html", null ]
                ] ],
                [ "PolyRingQuotient", "dd/dc9/class_poly_ring_quotient.html", null ]
              ] ]
            ] ],
            [ "RingZZ", "d8/d2b/class_ring_z_z.html", null ],
            [ "SchurRing2", "df/da2/class_schur_ring2.html", [
              [ "SchurSnRing", "d7/d6f/class_schur_sn_ring.html", null ]
            ] ],
            [ "Tower", "d2/dcb/class_tower.html", null ],
            [ "Z_mod", "d7/d1a/class_z__mod.html", null ]
          ] ],
          [ "SLP< Field >", "da/d22/class_s_l_p.html", null ],
          [ "SLP< ComplexField >", "da/d22/class_s_l_p.html", [
            [ "StraightLineProgram", "d5/df6/class_straight_line_program.html", null ]
          ] ]
        ] ]
      ] ],
      [ "part_elem", "d4/d27/structpart__elem.html", null ],
      [ "PfaffianComputation", "dc/df6/class_pfaffian_computation.html", null ],
      [ "Polynomial< CoefficientRingType >", "d6/db7/class_polynomial.html", null ],
      [ "PolynomialHeap", "d7/d5e/class_polynomial_heap.html", [
        [ "MapPolynomialHeap", "d3/d6a/class_map_polynomial_heap.html", null ],
        [ "NaiveDedupPolynomialHeap< Queue >", "d8/ded/class_naive_dedup_polynomial_heap.html", null ],
        [ "NaivePolynomialHeap< Queue >", "d1/dc6/class_naive_polynomial_heap.html", null ],
        [ "PriorityQueuePolynomialHeap", "de/d49/class_priority_queue_polynomial_heap.html", null ],
        [ "TrivialPolynomialHeap", "d4/d7a/class_trivial_polynomial_heap.html", null ]
      ] ],
      [ "pre_spair", "d1/deb/structpre__spair.html", null ],
      [ "QRingInfo", "d2/da2/class_q_ring_info.html", [
        [ "QRingInfo_field", "d5/d13/class_q_ring_info__field.html", [
          [ "QRingInfo_field_basic", "da/d22/class_q_ring_info__field__basic.html", null ],
          [ "QRingInfo_field_QQ", "d2/d56/class_q_ring_info__field___q_q.html", null ]
        ] ],
        [ "QRingInfo_ZZ", "dc/d6c/class_q_ring_info___z_z.html", null ]
      ] ],
      [ "queue_block< T >", "d6/da7/classqueue__block.html", null ],
      [ "queue_block< int_bag * >", "d6/da7/classqueue__block.html", null ],
      [ "queue_block< long >", "d6/da7/classqueue__block.html", null ],
      [ "res2_level", "d7/dcd/structres2__level.html", null ],
      [ "res2_pair", "d0/d5c/structres2__pair.html", null ],
      [ "res2_poly", "d8/da3/classres2__poly.html", null ],
      [ "res2term", "d2/dbf/structres2term.html", null ],
      [ "res_degree", "dd/d86/classres__degree.html", null ],
      [ "res_level", "d1/d07/classres__level.html", null ],
      [ "res_poly", "d6/dac/classres__poly.html", null ],
      [ "ResF4MonomialLookupTableT< Key >", "da/d5f/class_res_f4_monomial_lookup_table_t.html", null ],
      [ "ResF4MonomialLookupTableT< Key >::mi_node", "d9/dc9/struct_res_f4_monomial_lookup_table_t_1_1mi__node.html", null ],
      [ "ResGausser", "df/d88/class_res_gausser.html", [
        [ "ResGausserQQ", "d1/dff/class_res_gausser_q_q.html", null ],
        [ "ResGausserQQHybrid", "d4/d2e/class_res_gausser_q_q_hybrid.html", null ],
        [ "ResGausserZZp", "d5/de8/class_res_gausser_z_zp.html", null ]
      ] ],
      [ "ResPolyRing", "d1/d4c/class_res_poly_ring.html", null ],
      [ "RingMap::var", "d4/d7d/struct_ring_map_1_1var.html", null ],
      [ "row_elem", "dc/d50/structrow__elem.html", null ],
      [ "s_pair", "d8/d45/structs__pair.html", null ],
      [ "s_pair_heap", "db/d49/classs__pair__heap.html", null ],
      [ "SchreyerOrder", "d4/d92/class_schreyer_order.html", null ],
      [ "schur_poly", "d9/d25/classschur__poly.html", null ],
      [ "schur_poly_heap", "d7/d0c/classschur__poly__heap.html", null ],
      [ "slab", "dc/d02/classslab.html", null ],
      [ "SMat< ACoeffRing >::iterator", "dc/dde/class_s_mat_1_1iterator.html", null ],
      [ "SMat< ACoeffRing >::sparsevec", "d7/d3d/struct_s_mat_1_1sparsevec.html", null ],
      [ "spair", "d5/dc0/structspair.html", null ],
      [ "sparse_row", "df/d30/structsparse__row.html", null ],
      [ "stash", "d1/d5b/classstash.html", null ],
      [ "SumCollector", "da/d60/class_sum_collector.html", [
        [ "SumCollectorDefault", "d0/de7/class_sum_collector_default.html", null ],
        [ "SumCollectorFreeAlgebraHeap", "d3/d26/class_sum_collector_free_algebra_heap.html", null ],
        [ "SumCollectorPolyHeap", "d8/d2f/class_sum_collector_poly_heap.html", null ]
      ] ],
      [ "TowerPolynomial", "da/dd1/struct_tower_polynomial_struct.html", null ],
      [ "vec", "d6/ddd/structvecterm.html", null ]
    ] ],
    [ "OurQueueConfiguration", "d1/d7c/class_our_queue_configuration.html", null ],
    [ "OurQueueConfiguration1", "d4/d77/class_our_queue_configuration1.html", null ],
    [ "OverlapTable", "de/d48/class_overlap_table.html", null ],
    [ "Pair", "d2/d49/class_pair.html", null ],
    [ "PairRange< U, T >", "df/d71/class_pair_range.html", null ],
    [ "partition_table", "dc/d6e/classpartition__table.html", null ],
    [ "PointArray", "d2/dbf/class_point_array.html", null ],
    [ "BIBasis::PointerLessComparator< T >", "db/d78/class_b_i_basis_1_1_pointer_less_comparator.html", null ],
    [ "BIBasis::PointerMoreComparator< T >", "d1/d63/class_b_i_basis_1_1_pointer_more_comparator.html", null ],
    [ "PointsComputation< CoeffRing >", "d2/d6c/class_points_computation.html", null ],
    [ "POLY", "d0/d03/struct_p_o_l_y.html", null ],
    [ "polyheap", "d3/d5a/classpolyheap.html", null ],
    [ "BIBasis::Polynom< MonomType >", "d9/d02/class_b_i_basis_1_1_polynom.html", null ],
    [ "SchreyerFrameTypes::PreElement", "d9/d02/struct_schreyer_frame_types_1_1_pre_element.html", null ],
    [ "NCF4::PreRow", "df/d6f/struct_n_c_f4_1_1_pre_row.html", null ],
    [ "PreSPairSorter", "d0/de8/class_pre_s_pair_sorter.html", null ],
    [ "std::priority_queue< T >", null, null ],
    [ "std::priority_queue< Entry, Container, EntryConfig >", null, null ],
    [ "BIBasis::QSet< MonomType >", "df/d3f/class_b_i_basis_1_1_q_set.html", null ],
    [ "queue< T >", "db/da9/classqueue.html", null ],
    [ "std::queue< T >", null, null ],
    [ "queue< int_bag * >", "db/da9/classqueue.html", null ],
    [ "queue< long >", "db/da9/classqueue.html", null ],
    [ "QuickSorter< Sorter >", "d5/d18/class_quick_sorter.html", null ],
    [ "Range< T >", "dc/d37/class_range.html", null ],
    [ "Range< int >", "dc/d37/class_range.html", null ],
    [ "Range< U >", "dc/d37/class_range.html", null ],
    [ "Range< Word >", "dc/d37/class_range.html", null ],
    [ "M2::Reader< RingType >", "db/dc5/class_m2_1_1_reader.html", null ],
    [ "std::recursive_mutex", null, null ],
    [ "std::recursive_timed_mutex", null, null ],
    [ "RElement", "d5/de8/class_r_element.html", [
      [ "M2::RElementWrap< RingType >", "d1/da0/class_m2_1_1_r_element_wrap.html", null ]
    ] ],
    [ "res_pair", "dc/d2a/classres__pair.html", null ],
    [ "res_varpower_monomials", "d3/df0/classres__varpower__monomials.html", null ],
    [ "ResF4toM2Interface", "d2/d32/class_res_f4to_m2_interface.html", null ],
    [ "ResMonoidDense", "dc/d0d/class_res_monoid_dense.html", null ],
    [ "ResMonoidSparse", "d5/df9/class_res_monoid_sparse.html", null ],
    [ "ResMonomialsIgnoringComponent", "d1/dac/class_res_monomials_ignoring_component.html", null ],
    [ "ResMonomialSorter", "d8/d9c/class_res_monomial_sorter.html", null ],
    [ "ResMonomialsWithComponent", "d8/d28/class_res_monomials_with_component.html", null ],
    [ "ResPolynomial", "db/d8e/class_res_polynomial.html", null ],
    [ "ResPolynomialConstructor", "d7/d3d/class_res_polynomial_constructor.html", null ],
    [ "ResPolynomialIterator", "df/db4/class_res_polynomial_iterator.html", null ],
    [ "ResSchreyerOrder", "df/de7/struct_res_schreyer_order.html", null ],
    [ "resterm", "d9/d1b/structresterm.html", null ],
    [ "mpfr::internal::result_type< ArgumentType >", "d2/dbe/structmpfr_1_1internal_1_1result__type.html", null ],
    [ "mpfr::internal::result_type< double >", "d8/da4/structmpfr_1_1internal_1_1result__type_3_01double_01_4.html", null ],
    [ "mpfr::internal::result_type< int >", "d4/d9d/structmpfr_1_1internal_1_1result__type_3_01int_01_4.html", null ],
    [ "mpfr::internal::result_type< long double >", "d0/d3e/structmpfr_1_1internal_1_1result__type_3_01long_01double_01_4.html", null ],
    [ "mpfr::internal::result_type< long int >", "da/ddd/structmpfr_1_1internal_1_1result__type_3_01long_01int_01_4.html", null ],
    [ "mpfr::internal::result_type< long long >", "d5/d5e/structmpfr_1_1internal_1_1result__type_3_01long_01long_01_4.html", null ],
    [ "mpfr::internal::result_type< mpq_t >", "d9/d6c/structmpfr_1_1internal_1_1result__type_3_01mpq__t_01_4.html", null ],
    [ "mpfr::internal::result_type< mpreal >", "d3/d4a/structmpfr_1_1internal_1_1result__type_3_01mpreal_01_4.html", null ],
    [ "mpfr::internal::result_type< mpz_t >", "d2/db6/structmpfr_1_1internal_1_1result__type_3_01mpz__t_01_4.html", null ],
    [ "mpfr::internal::result_type< unsigned int >", "d5/df9/structmpfr_1_1internal_1_1result__type_3_01unsigned_01int_01_4.html", null ],
    [ "mpfr::internal::result_type< unsigned long int >", "dc/db2/structmpfr_1_1internal_1_1result__type_3_01unsigned_01long_01int_01_4.html", null ],
    [ "mpfr::internal::result_type< unsigned long long >", "db/df4/structmpfr_1_1internal_1_1result__type_3_01unsigned_01long_01long_01_4.html", null ],
    [ "std::basic_string< Char >::reverse_iterator", null, null ],
    [ "std::wstring::reverse_iterator", null, null ],
    [ "std::map< K, T >::reverse_iterator", null, null ],
    [ "std::unordered_set< K >::reverse_iterator", null, null ],
    [ "std::u32string_view::reverse_iterator", null, null ],
    [ "std::forward_list< T >::reverse_iterator", null, null ],
    [ "std::unordered_multimap< K, T >::reverse_iterator", null, null ],
    [ "std::u16string::reverse_iterator", null, null ],
    [ "std::wstring_view::reverse_iterator", null, null ],
    [ "std::u32string::reverse_iterator", null, null ],
    [ "std::multiset< K >::reverse_iterator", null, null ],
    [ "std::multimap< K, T >::reverse_iterator", null, null ],
    [ "std::unordered_multiset< K >::reverse_iterator", null, null ],
    [ "std::u8string::reverse_iterator", null, null ],
    [ "std::array< T >::reverse_iterator", null, null ],
    [ "std::basic_string_view< Char >::reverse_iterator", null, null ],
    [ "std::vector< T >::reverse_iterator", null, null ],
    [ "std::string_view::reverse_iterator", null, null ],
    [ "std::span< T >::reverse_iterator", null, null ],
    [ "std::set< K >::reverse_iterator", null, null ],
    [ "std::unordered_map< K, T >::reverse_iterator", null, null ],
    [ "std::u8string_view::reverse_iterator", null, null ],
    [ "std::u16string_view::reverse_iterator", null, null ],
    [ "std::string::reverse_iterator", null, null ],
    [ "std::list< T >::reverse_iterator", null, null ],
    [ "std::deque< T >::reverse_iterator", null, null ],
    [ "ring_elem", "d5/d64/unionring__elem.html", null ],
    [ "RingElementGenerator< RingType >", "df/d9f/class_ring_element_generator.html", null ],
    [ "NCF4::Row", "d8/d29/struct_n_c_f4_1_1_row.html", null ],
    [ "F4Res::Row", "d9/d66/struct_f4_res_1_1_row.html", null ],
    [ "sagbi", "dc/d5a/classsagbi.html", null ],
    [ "SchreyerFrame", "dd/d1a/class_schreyer_frame.html", null ],
    [ "SchreyerOrder_symm", "dc/d2a/struct_schreyer_order__symm.html", null ],
    [ "schur_poly_iterator", "d7/d11/classschur__poly__iterator.html", null ],
    [ "std::set< K >", null, null ],
    [ "std::set< typename MonomType::Integer >", null, null ],
    [ "BIBasis::SettingsManager", "dd/dbf/class_b_i_basis_1_1_settings_manager.html", null ],
    [ "std::shared_lock< T >", null, null ],
    [ "std::shared_mutex", null, null ],
    [ "std::shared_ptr< T >", null, null ],
    [ "std::shared_timed_mutex", null, null ],
    [ "SkewMultiplication", "d0/d29/class_skew_multiplication.html", null ],
    [ "MemoryBlock< T, NSLAB >::slab", "d5/d90/struct_memory_block_1_1slab.html", null ],
    [ "SLEvaluator", "d0/d4e/class_s_l_evaluator.html", [
      [ "SLEvaluatorConcrete< RT >", "d2/dbe/class_s_l_evaluator_concrete.html", null ]
    ] ],
    [ "SLProgram", "d3/dd3/class_s_l_program.html", null ],
    [ "std::smart_ptr< T >", null, null ],
    [ "SMat< ACoeffRing >", "da/de0/class_s_mat.html", null ],
    [ "SMat< CoeffRing >", "da/de0/class_s_mat.html", null ],
    [ "Solution", "da/dc2/struct_solution.html", null ],
    [ "gbA::spair", "df/deb/structgb_a_1_1spair.html", null ],
    [ "gbB::spair", "d6/dc8/structgb_b_1_1spair.html", null ],
    [ "std::span< T >", null, null ],
    [ "SPolySorter", "d7/df0/class_s_poly_sorter.html", null ],
    [ "SPolySorterB", "d5/d25/class_s_poly_sorter_b.html", null ],
    [ "std::stack< T >", null, null ],
    [ "StatsAllocator< T >", "d9/dd2/class_stats_allocator.html", null ],
    [ "StopConditions", "d6/d5d/struct_stop_conditions.html", null ],
    [ "SubMatrix< MatType >", "d3/da1/struct_sub_matrix.html", null ],
    [ "Subsets", "da/d91/class_subsets.html", null ],
    [ "SuffixTree", "d7/df2/class_suffix_tree.html", null ],
    [ "SuffixTreeNode", "dc/dad/class_suffix_tree_node.html", null ],
    [ "SymmMatrix", "db/d15/class_symm_matrix.html", null ],
    [ "std::system_error", null, null ],
    [ "Table_T", "d6/d47/struct_table___t.html", null ],
    [ "tableau", "d8/dee/classtableau.html", null ],
    [ "tableau2", "dd/d69/classtableau2.html", null ],
    [ "std::thread", null, null ],
    [ "std::timed_mutex", null, null ],
    [ "BIBasis::Triple< MonomType >", "da/d09/class_b_i_basis_1_1_triple.html", null ],
    [ "TrivialHomotopyAlgorithm", "d5/da7/class_trivial_homotopy_algorithm.html", null ],
    [ "BIBasis::TSet< MonomType >", "d3/d5c/class_b_i_basis_1_1_t_set.html", null ],
    [ "std::unique_lock< T >", null, null ],
    [ "std::unique_ptr< T >", null, null ],
    [ "std::unique_ptr< const ResGausser >", null, null ],
    [ "std::unique_ptr< const ResMonoidDense >", null, null ],
    [ "std::unique_ptr< const ResMonomialsWithComponent >", null, null ],
    [ "std::unique_ptr< F4Res >", null, null ],
    [ "std::unique_ptr< FreeAlgebra >", null, null ],
    [ "std::unique_ptr< FreeAlgebraQuotient >", null, null ],
    [ "std::unique_ptr< Homotopy >", null, null ],
    [ "std::unique_ptr< PointArray >", null, null ],
    [ "std::unique_ptr< PolynomialHeap >", null, null ],
    [ "std::unique_ptr< res_monomial_word[]>", null, null ],
    [ "std::unique_ptr< ResPolyRing >", null, null ],
    [ "std::unique_ptr< SchreyerFrame >", null, null ],
    [ "std::unique_ptr< SLProgram >", null, null ],
    [ "std::unique_ptr< value[]>", null, null ],
    [ "std::unique_ptr< WordTable >", null, null ],
    [ "std::unordered_map< K, T >", null, null ],
    [ "std::unordered_multimap< K, T >", null, null ],
    [ "std::unordered_multiset< K >", null, null ],
    [ "std::unordered_set< K >", null, null ],
    [ "std::unordered_set< const int *, MonomialHashAndEqFixedSize, MonomialHashAndEqFixedSize >", null, null ],
    [ "std::unordered_set< const int *, MonomialHashAndEqVarSize, MonomialHashAndEqVarSize >", null, null ],
    [ "std::unordered_set< ModuleMonom, ModuleMonomHash, ModuleMonomEq >", null, null ],
    [ "std::valarray< T >", null, null ],
    [ "VariablePrecisionHomotopyAlgorithm", "d4/d16/class_variable_precision_homotopy_algorithm.html", null ],
    [ "varpower", "d3/ded/classvarpower.html", null ],
    [ "varpower_monomials", "d6/dec/classvarpower__monomials.html", null ],
    [ "BIBasis::Monom::VarsListNode", "d6/d0c/struct_b_i_basis_1_1_monom_1_1_vars_list_node.html", null ],
    [ "vecHeap", "d1/d2c/classvec_heap.html", null ],
    [ "std::vector< T >", null, null ],
    [ "std::vector< binomial_gb_elem *, gc_allocator< binomial_gb_elem * > >", null, null ],
    [ "std::vector< bool >", null, null ],
    [ "std::vector< Column >", null, null ],
    [ "std::vector< component_index >", null, null ],
    [ "std::vector< const_monomial, gc_allocator< const_monomial > >", null, null ],
    [ "std::vector< double >", null, null ],
    [ "std::vector< ElementType >", null, null ],
    [ "std::vector< ElementType, gc_allocator< ElementType > >", null, null ],
    [ "std::vector< F4Res::Row >", null, null ],
    [ "std::vector< GATE_TYPE >", null, null ],
    [ "std::vector< gb_elem *, gc_allocator< gb_elem * > >", null, null ],
    [ "std::vector< gbA::gbelem *, gc_allocator< gbA::gbelem * > >", null, null ],
    [ "std::vector< gbB::gbelem *, gc_allocator< gbB::gbelem * > >", null, null ],
    [ "std::vector< gbvector *, gc_allocator< gbvector * > >", null, null ],
    [ "std::vector< hm_elem *, gc_allocator< hm_elem * > >", null, null ],
    [ "std::vector< int * >", null, null ],
    [ "std::vector< int *, gc_allocator< int * > >", null, null ],
    [ "std::vector< int >", null, null ],
    [ "std::vector< int, gc_allocator< int > >", null, null ],
    [ "std::vector< Label >", null, null ],
    [ "std::vector< long >", null, null ],
    [ "std::vector< M2::ARingPolynomialStruct >", null, null ],
    [ "std::vector< M2_arrayint, gc_allocator< M2_arrayint > >", null, null ],
    [ "std::vector< MemoryBlock * >", null, null ],
    [ "std::vector< ModuleMonom >", null, null ],
    [ "std::vector< monideal_pair *, gc_allocator< monideal_pair * > >", null, null ],
    [ "std::vector< MonomialIdeal *, gc_allocator< MonomialIdeal * > >", null, null ],
    [ "std::vector< MonomialTable::mon_term *, gc_allocator< MonomialTable::mon_term * > >", null, null ],
    [ "std::vector< MonomialTableZZ::mon_term *, gc_allocator< MonomialTableZZ::mon_term * > >", null, null ],
    [ "std::vector< mpz_srcptr, gc_allocator< mpz_srcptr > >", null, null ],
    [ "std::vector< MutableMatrix *, gc_allocator< MutableMatrix * > >", null, null ],
    [ "std::vector< NCF4::PreRow >", null, null ],
    [ "std::vector< Nterm *, gc_allocator< Nterm * > >", null, null ],
    [ "std::vector< Poly *, gc_allocator< Poly * > >", null, null ],
    [ "std::vector< POLY, gc_allocator< POLY > >", null, null ],
    [ "std::vector< RealVector >", null, null ],
    [ "std::vector< ReducedGB_Field_Local::divisor_info, gc_allocator< ReducedGB_Field_Local::divisor_info > >", null, null ],
    [ "std::vector< res2_level *, gc_allocator< res2_level * > >", null, null ],
    [ "std::vector< res2_pair *, gc_allocator< res2_pair * > >", null, null ],
    [ "std::vector< res_degree *, gc_allocator< res_degree * > >", null, null ],
    [ "std::vector< res_level *, gc_allocator< res_level * > >", null, null ],
    [ "std::vector< res_monomial_word >", null, null ],
    [ "std::vector< res_packed_monomial >", null, null ],
    [ "std::vector< res_pair *, gc_allocator< res_pair * > >", null, null ],
    [ "std::vector< ring_elem, gc_allocator< ring_elem > >", null, null ],
    [ "std::vector< Row, gc_allocator< Row > >", null, null ],
    [ "std::vector< SchreyerFrame::Level >", null, null ],
    [ "std::vector< SchreyerFrameTypes::FrameElement >", null, null ],
    [ "std::vector< size_t >", null, null ],
    [ "std::vector< SLProgram::GATE_TYPE >", null, null ],
    [ "std::vector< std::pair< int, int > >", null, null ],
    [ "std::vector< std::string >", null, null ],
    [ "std::vector< vec, gc_allocator< vec > >", null, null ],
    [ "std::vector< Word >", null, null ],
    [ "std::vector< WordWithData >", null, null ],
    [ "VectorArithmetic", "d1/df6/class_vector_arithmetic.html", null ],
    [ "std::weak_ptr< T >", null, null ],
    [ "Word", "d3/da0/class_word.html", null ],
    [ "WordTable", "d6/def/class_word_table.html", null ],
    [ "WordWithData", "d2/d05/class_word_with_data.html", null ],
    [ "WordWithDataTable", "dd/d60/class_word_with_data_table.html", null ],
    [ "ZipIterator< U, T >", "d3/def/class_zip_iterator.html", null ],
    [ "__mpfr_struct", null, null ],
    [ "Arena", null, null ],
    [ "Arena *", null, null ],
    [ "bool", "d9/db9/classbool.html", null ],
    [ "brMonomial", null, null ],
    [ "char", null, null ],
    [ "clock_t", "da/d53/classclock__t.html", null ],
    [ "CoefficientType", null, null ],
    [ "column_array", null, null ],
    [ "column_array &", null, null ],
    [ "component_index", null, null ],
    [ "Configuration", null, null ],
    [ "const ACoeffRing *", null, null ],
    [ "const ARing *", null, null ],
    [ "const CoeffRing *", null, null ],
    [ "const ElementType *", null, null ],
    [ "const FieldType", null, null ],
    [ "const gb_array &", null, null ],
    [ "const MonomType *", null, null ],
    [ "const RingType &", null, null ],
    [ "const RingType *", null, null ],
    [ "const RT &", null, null ],
    [ "const RT *", null, null ],
    [ "const U *", null, null ],
    [ "const ValueType *", null, null ],
    [ "const void *", null, null ],
    [ "const_iterator", null, null ],
    [ "const_iterator", null, null ],
    [ "const_monomial", null, null ],
    [ "const_varpower_monomial", null, null ],
    [ "deg_t *", null, null ],
    [ "double", null, null ],
    [ "elem", null, null ],
    [ "Element", null, null ],
    [ "element_type *", null, null ],
    [ "ElementType", null, null ],
    [ "ElementType", null, null ],
    [ "ElementType", null, null ],
    [ "ElementType", null, null ],
    [ "ElementType *", null, null ],
    [ "ElementType *", null, null ],
    [ "Entry", null, null ],
    [ "enum ComputationStatusCode", null, null ],
    [ "enum factoryCoeffMode", null, null ],
    [ "enum MonomialOrdering_type", null, null ],
    [ "enum spair_type", null, null ],
    [ "Field", null, null ],
    [ "flint_rand_t", null, null ],
    [ "fmpq_mat_t", null, null ],
    [ "fmpz_mat_t", null, null ],
    [ "fmpz_t", null, null ],
    [ "fq_nmod_ctx_t", null, null ],
    [ "fq_nmod_mat_t", null, null ],
    [ "fq_nmod_struct", null, null ],
    [ "fq_zech_ctx_t", null, null ],
    [ "fq_zech_mat_t", null, null ],
    [ "fq_zech_struct", null, null ],
    [ "FREEMODULETYPE *", null, null ],
    [ "GATE_TYPE", null, null ],
    [ "gb_array", null, null ],
    [ "gbA_state", null, null ],
    [ "gbB_state", null, null ],
    [ "gbelem_type", null, null ],
    [ "GeobucketBucketStorage", null, null ],
    [ "gmp_randstate_t", null, null ],
    [ "gmp_RR", null, null ],
    [ "int", "d1/da0/classint.html", null ],
    [ "Integer", null, null ],
    [ "Integer", null, null ],
    [ "Integer", null, null ],
    [ "JanetTree< MonomType >", null, null ],
    [ "K", null, null ],
    [ "Key", null, null ],
    [ "long", null, null ],
    [ "M2_arrayint", "d8/dc2/class_m2__arrayint.html", null ],
    [ "M2_ArrayString", null, null ],
    [ "M2_bool", null, null ],
    [ "Mat", null, null ],
    [ "MatType &", null, null ],
    [ "mon_part", null, null ],
    [ "MonomialOrder *", null, null ],
    [ "MonomType *", null, null ],
    [ "mp_limb_t", null, null ],
    [ "mpfi_srcptr", null, null ],
    [ "mpfr_ptr", null, null ],
    [ "mpfr_srcptr", null, null ],
    [ "mpfr_t", null, null ],
    [ "mpq_srcptr", null, null ],
    [ "mpz_srcptr", null, null ],
    [ "mpz_t", null, null ],
    [ "myword", null, null ],
    [ "nmod_mat_t", null, null ],
    [ "nmod_t", null, null ],
    [ "ntuple_word *", null, null ],
    [ "Order", null, null ],
    [ "overflow_type *", null, null ],
    [ "Overlap", null, null ],
    [ "pair< int, bool >", null, null ],
    [ "pair< int, int >", null, null ],
    [ "pair< Monom, ring_elem >", null, null ],
    [ "pair< size_t, size_t >", null, null ],
    [ "Polynom< MonomType > *", null, null ],
    [ "Polynom< MonomType > *", null, null ],
    [ "Polynomial< CoefficientRingType >", null, null ],
    [ "PreRowType", null, null ],
    [ "QSet< MonomType >", null, null ],
    [ "Queue< NaiveDedupQueueConfiguration >", null, null ],
    [ "Queue< NaiveQueueConfiguration >", null, null ],
    [ "queue_block< T > *", null, null ],
    [ "queuing_mutex", null, null ],
    [ "RandIter", null, null ],
    [ "Range< T >", null, null ],
    [ "res_const_varpower_monomial", null, null ],
    [ "res_monomial_word", null, null ],
    [ "res_monomial_word *", null, null ],
    [ "res_monomial_word *", null, null ],
    [ "res_packed_monomial", null, null ],
    [ "res_varpower_word", null, null ],
    [ "res_varpower_word *", null, null ],
    [ "res_varpower_word *", null, null ],
    [ "Residu_t", null, null ],
    [ "RingType", null, null ],
    [ "row_array", null, null ],
    [ "size_t", null, null ],
    [ "SolutionStatus", null, null ],
    [ "Sorter *", null, null ],
    [ "SPAIR", null, null ],
    [ "spair_type", null, null ],
    [ "spinLock", null, null ],
    [ "static const float_denorm_style", null, null ],
    [ "static const RingID", null, null ],
    [ "static int", "da/dcb/classstatic_01int.html", null ],
    [ "static Integer", null, null ],
    [ "static MonomType", null, null ],
    [ "static SLP< Field > *", null, null ],
    [ "T", null, null ],
    [ "task_arena", null, null ],
    [ "TowerPolynomial", null, null ],
    [ "Triple< MonomType > *", null, null ],
    [ "Triple< MonomType > *", null, null ],
    [ "Ts", "dc/d68/class_ts.html", [
      [ "overloaded< Ts >", "d9/d94/structoverloaded.html", null ]
    ] ],
    [ "TSet< MonomType >", null, null ],
    [ "U *", null, null ],
    [ "U *", null, null ],
    [ "uint32_t", null, null ],
    [ "ulong *", null, null ],
    [ "unordered_map< Word, std::pair< int, int >, MonomHash, MonomHashEqual >", null, null ],
    [ "unsigned", null, null ],
    [ "unsigned short", null, null ],
    [ "unsigned(*)(const void *key)", null, null ],
    [ "value", null, null ],
    [ "value *", null, null ],
    [ "variant< ConcreteVectorArithmetic< M2::ARingZZpFlint > *, ConcreteVectorArithmetic< M2::ARingGFFlintBig > *, ConcreteVectorArithmetic< M2::ARingGFFlint > *, ConcreteVectorArithmetic< M2::ARingQQGMP > *, ConcreteVectorArithmetic< M2::ARingZZpFFPACK > *, ConcreteVectorArithmetic< M2::ARingZZp > *, ConcreteVectorArithmetic< M2::ARingGFM2 > *, ConcreteVectorArithmetic< M2::ARingGFGivaro > *, ConcreteVectorArithmetic< CoefficientRingR > *, ConcreteVectorArithmetic< CoefficientRingZZp > *, ConcreteVectorArithmetic< M2::DummyRing > * >", null, null ],
    [ "vec", null, null ],
    [ "VECTYPE", null, null ],
    [ "void *", null, null ],
    [ "void **", null, null ],
    [ "void(*)(element_type *, element_type *)", "de/d78/classvoid_07_5_08_07element__type_01_5_00_01element__type_01_5_08.html", null ],
    [ "void(*)(element_type *, element_type *)", null, null ]
];