Macaulay2 Engine: gbB::spair_set_insert
spair_set_insert()
void gbB::spair_set_insert (gbB::spair * p) private
Definition at line 792 of file gb-test1.cpp.
 {
   while (p != 0)
     {
       spair_set_lead_spoly(p);
       spair *tmp = p;
       p = p->next;
       S->nelems++;
       tmp->next = S->heap;
       S->heap = tmp;
     }
 }
References gbB::SPairSet::heap, gbB::SPairSet::nelems, gbB::spair::next, p, S, and spair_set_lead_spoly().
Referenced by initialize(), minimalize_pairs(), and reduceit().