Macaulay2 Engine: gbB::do_computation
do_computation()
void gbB::do_computation () private
Definition at line 1554 of file gb-test1.cpp.
 {
   ComputationStatusCode ret;
   spair *p;
   // initial state is STATE_NEWDEGREE
   if (stop_.always_stop) return;  // don't change status
   if ((ret = computation_is_complete()) != COMP_COMPUTING)
     {
       set_status(ret);
       return;
     }
   if (M2_gbTrace == 15)
     {
       emit_line("[gb]");
     }
   else if (M2_gbTrace >= 1)
     {
       emit_wrapped("[gb]");
     }
   for (;;)
     {
       if (stop_.stop_after_degree && this_degree > stop_.degree_limit->array[0])
         {
           // Break out now if we don't have anything else to compute in this
           // degree.
           set_status(COMP_DONE_DEGREE_LIMIT);
           return;
         }
       if (M2_gbTrace & PrintingDegree)
         {
         }
       switch (state)
         {
           case STATE_NEWPAIRS:
             // Loop through all of the new GB elements, and
             // compute spairs.  Start at np_i
             // np_i is initialized at the beginning, and also here.
             while (np_i < n_gb)
               {
                 if (system_interrupted())
                   {
                     set_status(COMP_INTERRUPTED);
                     return;
                   }
                 if (gb[np_i]->minlevel & ELEMB_MINGB) update_pairs(np_i);
                 np_i++;
               }
             state = STATE_NEWDEGREE;
           case STATE_NEWDEGREE:
             // Get the spairs and generators for the next degree
             if (S->n_in_degree == 0)
               {
                 int old_degree = this_degree;
                 npairs = spair_set_prepare_next_degree(
                     this_degree);  // sets this_degree
                 if (old_degree < this_degree) first_in_degree = INTSIZE(gb);
                 complete_thru_this_degree = this_degree - 1;
                 if (npairs == 0)
                   {
                     state = STATE_DONE;
                     set_status(COMP_DONE);
                     return;
                   }
                 if (stop_.stop_after_degree &&
                     this_degree > stop_.degree_limit->array[0])
                   {
                     set_status(COMP_DONE_DEGREE_LIMIT);
                     return;
                   }
                 if (hilbert)
                   {
                     if (!hilbert->setDegree(this_degree))
                       {
                         if (error())
                           set_status(COMP_ERROR);
                         else
                           set_status(COMP_INTERRUPTED);
                         return;
                       }
                   }
               }
             if (M2_gbTrace == 15)
               {
                 buffer o;
                 o << "DEGREE " << this_degree;
                 o << ", number of spairs = " << npairs;
                 if (hilbert)
                   o << ", expected number in this degree = "
                     << hilbert->nRemainingExpected();
                 emit_line(o.str());
               }
             else if (M2_gbTrace >= 1)
               {
                 buffer o;
                 o << '{' << this_degree << '}';
                 o << '(';
                 if (hilbert) o << hilbert->nRemainingExpected() << ',';
                 o << npairs << ')';
                 emit_wrapped(o.str());
               }
             ar_i = n_gb;
             ar_j = ar_i + 1;
             state = STATE_SPAIRS;
           case STATE_SPAIRS:
           case STATE_GENS:
             // Compute the spairs for this degree
             while ((p = spair_set_next()) != 0)
               {
                 process_spair(p);
                 npairs--;
                 n_pairs_computed++;
                 if ((ret = computation_is_complete()) != COMP_COMPUTING)
                   {
                     set_status(ret);
                     return;
                   }
                 if (system_interrupted())
                   {
                     set_status(COMP_INTERRUPTED);
                     return;
                   }
               }
             state = STATE_AUTOREDUCE;
           // or state = STATE_NEWPAIRS
           case STATE_AUTOREDUCE:
             // This is still possibly best performed when inserting a new
             // element
             // Perform the necessary or desired auto-reductions
             while (ar_i < n_gb)
               {
                 while (ar_j < n_gb)
                   {
                     if (system_interrupted())
                       {
                         set_status(COMP_INTERRUPTED);
                         return;
                       }
                     R->gbvector_auto_reduce(F,
                                             Fsyz,
                                             gb[ar_i]->g.f,
                                             gb[ar_i]->g.fsyz,
                                             gb[ar_j]->g.f,
                                             gb[ar_j]->g.fsyz);
                     ar_j++;
                   }
                 ar_i++;
                 ar_j = ar_i + 1;
               }
             state = STATE_NEWPAIRS;
             break;
           case STATE_DONE:
             return;
         }
     }
 }
References StopConditions::always_stop, ar_i, ar_j, COMP_COMPUTING, COMP_DONE, COMP_DONE_DEGREE_LIMIT, COMP_ERROR, COMP_INTERRUPTED, complete_thru_this_degree, computation_is_complete(), StopConditions::degree_limit, ELEMB_MINGB, emit_line(), emit_wrapped(), error(), F, first_in_degree, Fsyz, gb, GBRing::gbvector_auto_reduce(), hilbert, INTSIZE, M2_gbTrace, n_gb, gbB::SPairSet::n_in_degree, n_pairs_computed, np_i, npairs, HilbertController::nRemainingExpected(), p, PrintingDegree, process_spair(), R, S, Computation::set_status(), HilbertController::setDegree(), spair_set_next(), spair_set_prepare_next_degree(), state, STATE_AUTOREDUCE, STATE_DONE, STATE_GENS, STATE_NEWDEGREE, STATE_NEWPAIRS, STATE_SPAIRS, Computation::stop_, StopConditions::stop_after_degree, buffer::str(), system_interrupted(), this_degree, and update_pairs().
Referenced by start_computation().