Macaulay2 Engine: gbB::compute_s_pair
compute_s_pair()
void gbB::compute_s_pair (spair * p) private
Definition at line 1057 of file gb-test1.cpp.
 {
   POLY f, g;
   if (M2_gbTrace >= 5 && M2_gbTrace != 15)
     {
       buffer o;
       spair_text_out(o, p);
       emit_line(o.str());
     }
   if (p->type > SPAIR_SKEW) return;
   R->gbvector_remove(p->lead_of_spoly);
   p->lead_of_spoly = 0;
   f = gb[p->x.pair.i]->g;
   if (p->type == SPAIR_SKEW)
     {
       const int *mon = R->skew_monomial_var(p->x.pair.j);
       R->gbvector_mult_by_term(
           F, Fsyz, R->one(), mon, f.f, f.fsyz, p->f(), p->fsyz());
     }
   else
     {
       g = gb[p->x.pair.j]->g;
       R->gbvector_cancel_lead_terms(
           F, Fsyz, f.f, f.fsyz, g.f, g.fsyz, p->f(), p->fsyz());
     }
   p->type = SPAIR_ELEM;
   if (M2_gbTrace >= 5 && M2_gbTrace != 15)
     {
       buffer o;
       o << "    ";
       R->gbvector_text_out(o, F, p->f());
       emit_line(o.str());
     }
 }
References emit_line(), POLY::f, F, POLY::fsyz, Fsyz, gb, GBRing::gbvector_cancel_lead_terms(), GBRing::gbvector_mult_by_term(), GBRing::gbvector_remove(), GBRing::gbvector_text_out(), M2_gbTrace, GBRing::one(), p, R, GBRing::skew_monomial_var(), SPAIR_ELEM, SPAIR_SKEW, spair_text_out(), and buffer::str().
Referenced by reduceit().