Macaulay2 Engine: gbB::start_computation
start_computation()
void gbB::start_computation () virtual
Implements GBComputation.
Definition at line 1723 of file gb-test1.cpp.
 {
   ncalls = 0;
   nloops = 0;
   nsaved_unneeded = 0;
   do_computation();
   if (M2_gbTrace >= 1)
     {
       show_mem_usage();
       if (M2_gbTrace >= 3)
         {
           buffer o;
           o << "ncalls = " << ncalls;
           emit_line(o.str());
           o.reset();
           o << "nloop = " << nloops;
           emit_line(o.str());
           o.reset();
           o << "nsaved = " << nsaved_unneeded;
           emit_line(o.str());
         }
       if (M2_gbTrace >= 15) show();
     }
 }
References do_computation(), emit_line(), M2_gbTrace, ncalls, nloops, nsaved_unneeded, buffer::reset(), show(), show_mem_usage(), and buffer::str().