Macaulay2 Engine: gbB::spair_text_out
spair_text_out()
void gbB::spair_text_out (buffer & o, spair * p) private
Definition at line 425 of file gb-test1.cpp.
 {
   char s[100];  // enough room for all of the non polynomial cases.
   switch (p->type)
     {
       case SPAIR_SPAIR:
         sprintf(s, "spair(g%d,g%d):", p->x.pair.j, p->x.pair.i);
         o << s;
         sprintf(s, " deg %d", p->deg);
         o << s;
         o << " lcm exponents [";
         for (int i = 0; i < nvars + 2; i++)
           {
             sprintf(s, "%d ", p->lcm[i]);
             o << s;
           }
         o << "]";
         break;
       case SPAIR_GEN:
         o << "generator ";
         R->gbvector_text_out(o, F, p->f(), 3);
         break;
       case SPAIR_ELEM:
         o << "elem ";
         R->gbvector_text_out(o, F, p->f(), 3);
         break;
       case SPAIR_RING:
         sprintf(s, "rpair(%d,%d)", p->x.pair.i, p->x.pair.j);
         o << s;
         break;
       case SPAIR_SKEW:
         sprintf(s, "skewpair(g%d,g%d)", p->x.pair.j, p->x.pair.i);
         o << s;
         break;
       default:
         o << "unknown pair";
         break;
     }
 }
References F, GBRing::gbvector_text_out(), nvars, p, R, SPAIR_ELEM, SPAIR_GEN, SPAIR_RING, SPAIR_SKEW, and SPAIR_SPAIR.
Referenced by compute_s_pair(), debug_spair(), minimalize_pairs(), reduceit(), and remove_unneeded_pairs().