Macaulay2 Engine: gbB::minimalize_gb
minimalize_gb()
void gbB::minimalize_gb () private
Definition at line 1751 of file gb-test1.cpp.
 {
   if (minimal_gb_valid) return;
   delete minimal_gb;
   minimal_gb = ReducedGB::create(originalR, F, Fsyz);
   VECTOR(POLY) polys;
   for (int i = first_gb_element; i < gb.size(); i++)
     {
       if (gb[i]->minlevel & ELEMB_MINGB) polys.push_back(gb[i]->g);
     }
   minimal_gb->minimalize(polys);
   minimal_gb_valid = true;
 }
References ReducedGB::create(), ELEMB_MINGB, F, first_gb_element, Fsyz, gb, minimal_gb, minimal_gb_valid, ReducedGB::minimalize(), originalR, and VECTOR().
Referenced by contains(), get_change(), get_gb(), get_initial(), get_parallel_lead_terms(), matrix_lift(), and matrix_remainder().