Macaulay2 Engine: gbB::process_spair
process_spair()
bool gbB::process_spair (spair * p) private
Definition at line 1492 of file gb-test1.cpp.
 {
   stats_npairs++;
   bool not_deferred = reduceit(p);
   if (!not_deferred) return true;
   gbelem_type minlevel =
       (p->type == SPAIR_GEN ? ELEMB_MINGEN : 0) | ELEMB_MINGB;
   if (p->type == SPAIR_GEN) n_gens_left--;
   POLY f = p->x.f;
   p->x.f.f = 0;
   p->x.f.fsyz = 0;
   spair_delete(p);
   if (!R->gbvector_is_zero(f.f))
     {
       insert_gb(f, minlevel);
       if (M2_gbTrace == 3) emit_wrapped("m");
     }
   else
     {
       originalR->get_quotient_info()->gbvector_normal_form(Fsyz, f.fsyz);
       if (!R->gbvector_is_zero(f.fsyz))
         {
           /* This is a syzygy */
           collect_syzygy(f.fsyz);
           if (M2_gbTrace == 3) emit_wrapped("z");
         }
       else
         {
           if (M2_gbTrace == 3) emit_wrapped("o");
         }
     }
   return true;
 }
References collect_syzygy(), ELEMB_MINGB, ELEMB_MINGEN, emit_wrapped(), POLY::f, POLY::fsyz, Fsyz, GBRing::gbvector_is_zero(), QRingInfo::gbvector_normal_form(), PolynomialRing::get_quotient_info(), insert_gb(), M2_gbTrace, n_gens_left, originalR, p, R, reduceit(), spair_delete(), SPAIR_GEN, and stats_npairs.
Referenced by do_computation().