Macaulay2 Engine: gbB::gbelem_text_out
gbelem_text_out()
void gbB::gbelem_text_out (buffer & o, int i, int nterms = 3) const private
Definition at line 317 of file gb-test1.cpp.
 {
   gbelem_type minlevel = gb[i]->minlevel;
   bool ismingen = (minlevel & ELEMB_MINGEN);
   bool ismingb = (minlevel & ELEMB_MINGB);
   if (ismingb)
     o << "GB elem: ";
   else
     o << "reducer: ";
   o << "g" << i << " = ";
   R->gbvector_text_out(o, F, gb[i]->g.f, nterms);
   o << " ["
     << "gap " << gb[i]->gap << " size " << gb[i]->size << " deg " << gb[i]->deg
     << " rgap " << gb[i]->reduced_gap << " rdeg " << gb[i]->reduced_deg;
   if (ismingen) o << " mingen";
   o << "]";
 }
References ELEMB_MINGB, ELEMB_MINGEN, F, gb, GBRing::gbvector_text_out(), and R.
Referenced by insert_gb(), and show().