Macaulay2 Engine: gbB::find_good_divisor
find_good_divisor()
int gbB::find_good_divisor (exponents e, int x, int degf, int & result_gap) private
Definition at line 1190 of file gb-test1.cpp.
 {
   int n = 0;
   int gap;
   int egap = degf - weightInfo->exponents_weight(e, x);
   VECTOR(MonomialTable::mon_term *) divisors;
   if (divisor_previous >= 0 && x == divisor_previous_comp)
     {
       gbelem *tg = gb[divisor_previous];
       gap = tg->reduced_gap - egap;
       if (gap <= 0 && exponents_divide(nvars, tg->lead, e))
         {
           result_gap = 0;
           return divisor_previous;
         }
     }
   /* First search for ring divisors */
   if (ringtable) n += ringtable->find_divisors(-1, e, 1, &divisors);
   /* Next search for GB divisors */
   n += lookup->find_divisors(-1, e, x, &divisors);
   if (M2_gbTrace == 15 && n >= 2)
     {
       gbelem *tg = gb[divisors[n - 1]->_val];
       int sz = tg->size;
       if (sz >= 0)  // was 3, why??
         {
           buffer o;
           o << "    reducers: ";
           for (int j = 0; j < n; j++) o << "g" << divisors[j]->_val << " ";
           emit_line(o.str());
         }
     }
   /* Now find the minimal gap value */
   if (n == 0)
     {
       result_gap = 0;
       return -1;
     }
   int newgap;
   int result = divisors[n - 1]->_val;
   gbelem *tg = gb[result];
   gap = tg->reduced_gap - egap;
   if (gap <= 0)
     {
       gap = 0;
       int minsz = tg->size;
       for (int i = n - 2; i >= 0; i--)
         {
           int new_val = divisors[i]->_val;
           tg = gb[new_val];
           int sz = tg->size;
           if (sz < minsz)
             {
               if (tg->reduced_gap <= egap)
                 {
                   minsz = sz;
                   result = new_val;
                 }
             }
         }
     }
   else
     //    for (i=1; i<n; i++)
     for (int i = n - 2; i >= 0; i--)
       {
         int new_val = divisors[i]->_val;
         tg = gb[new_val];
         newgap = tg->reduced_gap - egap;
         if (newgap <= 0)
           {
             gap = 0;
             result = new_val;
             break;
           }
         else if (newgap < gap)
           {
             result = new_val;
             gap = newgap;
           }
       }
   divisor_previous = result;
   divisor_previous_comp = x;
   result_gap = gap;
   return result;
 }
References divisor_previous, divisor_previous_comp, emit_line(), exponents_divide(), GBWeight::exponents_weight(), MonomialTable::find_divisors(), gb, gbB::gbelem::lead, lookup, M2_gbTrace, nvars, gbB::gbelem::reduced_gap, ringtable, gbB::gbelem::size, buffer::str(), VECTOR(), weightInfo, and x.
Referenced by reduceit(), and remainder().