Macaulay2 Engine: gbB::exponents_make
exponents_make()
exponents gbB::exponents_make () private
Definition at line 29 of file gb-test1.cpp.
 {
   exponents result = reinterpret_cast<exponents>(lcm_stash->new_elem());
   return result;
 }
References lcm_stash, and stash::new_elem().
Referenced by gbelem_make(), gbelem_ring_make(), spair_make(), spair_make_gen(), and spair_make_skew().