Macaulay2 Engine: gbB::spair_set_lead_spoly
spair_set_lead_spoly()
void gbB::spair_set_lead_spoly (spair * p) private
Definition at line 1026 of file gb-test1.cpp.
 {
   gbvector *ltsyz = 0;
   POLY f, g;
   if (p->type > SPAIR_SKEW)
     {
       R->gbvector_remove(p->lead_of_spoly);
       p->lead_of_spoly = 0;
       return;
     }
   f = gb[p->x.pair.i]->g;
   if (p->type == SPAIR_SKEW)
     {
       const int *mon = R->skew_monomial_var(p->x.pair.j);
       R->gbvector_mult_by_term(
           F, Fsyz, R->one(), mon, f.f, 0, p->lead_of_spoly, ltsyz);
     }
   else
     {
       g = gb[p->x.pair.j]->g;
       R->gbvector_cancel_lead_terms(
           F, Fsyz, f.f, 0, g.f, 0, p->lead_of_spoly, ltsyz);
     }
   if (p->lead_of_spoly != 0)
     {
       gbvector *tmp = p->lead_of_spoly->next;
       p->lead_of_spoly->next = 0;
       R->gbvector_remove(tmp);
     }
 }
References POLY::f, F, Fsyz, gb, GBRing::gbvector_cancel_lead_terms(), GBRing::gbvector_mult_by_term(), GBRing::gbvector_remove(), GBRing::one(), p, R, GBRing::skew_monomial_var(), and SPAIR_SKEW.
Referenced by spair_set_insert().