Macaulay2 Engine: gbB::flush_pairs
flush_pairs()
void gbB::flush_pairs () private
Definition at line 1772 of file gb-test1.cpp.
 {
   spair *p;
   while ((p = spair_set_next()) != 0)
     {
       n_saved_hilb++;
       spair_delete(p);
     }
 }
References n_saved_hilb, p, spair_delete(), and spair_set_next().
Referenced by insert_gb().