Macaulay2 Engine: gbB::show
show()
void gbB::show () const virtual
Reimplemented from Computation.
Definition at line 1910 of file gb-test1.cpp.
 {
   buffer o;
   o << "Groebner basis, " << gb.size() << " elements";
   emit_line(o.str());
   o.reset();
   for (unsigned int i = 0; i < gb.size(); i++)
     {
       gbelem_text_out(o, i);
       emit_line(o.str());
       o.reset();
     }
 }
References emit_line(), gb, gbelem_text_out(), buffer::reset(), and buffer::str().
Referenced by start_computation().