Macaulay2 Engine: gbB::gbelem_make
gbelem_make()
gbB::gbelem * gbB::gbelem_make (gbvector * f, gbvector * fsyz, gbelem_type minlevel, int deg) private
Definition at line 294 of file gb-test1.cpp.
 {
   int f_wt, f_leadweight;
   gbelem *g = reinterpret_cast<gbelem *>(gbelem_stash->new_elem());
   g->g.f = f;
   g->g.fsyz = fsyz;
   g->lead = exponents_make();
   R->gbvector_get_lead_exponents(F, f, g->lead);
   g->deg = deg;
   f_wt = weightInfo->gbvector_weight(f, f_leadweight);
   g->gap =
       deg -
       f_leadweight;  // used to be: deg - weightInfo->gbvector_term_weight(f);
   g->reduced_deg = f_wt;
   g->reduced_gap = f_wt - f_leadweight;
   g->size = R->gbvector_n_terms(f);
   g->minlevel = minlevel;
   return g;
 }
References gbB::gbelem::deg, exponents_make(), POLY::f, F, POLY::fsyz, gbB::gbelem::g, gbB::gbelem::gap, gbelem_stash, GBRing::gbvector_get_lead_exponents(), GBRing::gbvector_n_terms(), GBWeight::gbvector_weight(), gbB::gbelem::lead, gbB::gbelem::minlevel, stash::new_elem(), R, gbB::gbelem::reduced_deg, gbB::gbelem::reduced_gap, gbB::gbelem::size, and weightInfo.
Referenced by insert_gb().