Macaulay2 Engine: gbB::gbelem_ring_make
gbelem_ring_make()
gbB::gbelem * gbB::gbelem_ring_make (gbvector * f) private
Definition at line 277 of file gb-test1.cpp.
 {
   int f_leadweight;
   gbelem *g = reinterpret_cast<gbelem *>(gbelem_stash->new_elem());
   g->g.f = f;
   g->g.fsyz = 0;
   g->lead = exponents_make();
   R->gbvector_get_lead_exponents(F, f, g->lead);
   g->deg = weightInfo->gbvector_weight(f, f_leadweight);
   g->gap = g->deg - f_leadweight;
   g->reduced_deg = g->deg;
   g->reduced_gap = g->gap;
   g->size = R->gbvector_n_terms(f);
   g->minlevel = ELEMB_IN_RING;
   return g;
 }
References gbB::gbelem::deg, ELEMB_IN_RING, exponents_make(), POLY::f, F, POLY::fsyz, gbB::gbelem::g, gbB::gbelem::gap, gbelem_stash, GBRing::gbvector_get_lead_exponents(), GBRing::gbvector_n_terms(), GBWeight::gbvector_weight(), gbB::gbelem::lead, gbB::gbelem::minlevel, stash::new_elem(), R, gbB::gbelem::reduced_deg, gbB::gbelem::reduced_gap, gbB::gbelem::size, and weightInfo.
Referenced by initialize().