Macaulay2 Engine: gbB::spair_make
spair_make()
gbB::spair * gbB::spair_make (int i, int j) private
Definition at line 360 of file gb-test1.cpp.
 {
   gbelem *g1 = gb[i];
   gbelem *g2 = gb[j];
   exponents exp1 = g1->lead;
   exponents exp2 = g2->lead;
   spair *result = spair_node();
   result->next = 0;
   result->type = SPAIR_SPAIR;
   result->lcm = exponents_make();
   exponents_lcm(
       nvars, g1->deg, exp1, exp2, result->lcm, gb_weights, result->deg);
   if (g2->gap > g1->gap) result->deg += g2->gap - g1->gap;
   result->x.pair.i = i;
   result->x.pair.j = j;
   return result;
 }
References gbB::gbelem::deg, gbB::spair::deg, mpfr::exp2(), exponents_lcm(), exponents_make(), gbB::gbelem::gap, gb, gb_weights, gbB::spair::lcm, gbB::gbelem::lead, gbB::spair::next, nvars, gbB::spair::pair, spair_node(), SPAIR_SPAIR, gbB::spair::type, and gbB::spair::x.
Referenced by spair_make_ring(), and update_pairs().