Macaulay2 Engine: gbB::spair_set_next
spair_set_next()
gbB::spair * gbB::spair_set_next () private
Definition at line 806 of file gb-test1.cpp.
 {
   spair *result = S->spair_list;
   if (result)
     {
       S->spair_list = result->next;
     }
   else
     {
       if (S->spair_deferred_list.next != 0)
         {
           if (M2_gbTrace >= 4)
             {
               emit_line("considering deferred pairs: ");
             }
           S->spair_list = S->spair_deferred_list.next;
           S->spair_deferred_list.next = 0;
           S->spair_last_deferred = &S->spair_deferred_list;
           result = S->spair_list;
           S->spair_list = result->next;
         }
       else
         {
           // Now do the same for generators
           result = S->gen_list;
           if (result)
             {
               S->gen_list = result->next;
             }
           else
             {
               if (S->gen_deferred_list.next != 0)
                 {
                   if (M2_gbTrace >= 4)
                     {
                       emit_line("  deferred gen pairs: ");
                     }
                   S->gen_list = S->gen_deferred_list.next;
                   S->gen_deferred_list.next = 0;
                   S->gen_last_deferred = &S->gen_deferred_list;
                   result = S->gen_list;
                   S->gen_list = result->next;
                 }
               else
                 return 0;
             }
         }
     }
   result->next = 0;
   S->nelems--;
   S->n_in_degree--;
   S->n_computed++;
   return result;
 }
References emit_line(), gbB::SPairSet::gen_deferred_list, gbB::SPairSet::gen_last_deferred, gbB::SPairSet::gen_list, M2_gbTrace, gbB::SPairSet::n_computed, gbB::SPairSet::n_in_degree, gbB::SPairSet::nelems, gbB::spair::next, S, gbB::SPairSet::spair_deferred_list, gbB::SPairSet::spair_last_deferred, and gbB::SPairSet::spair_list.
Referenced by do_computation(), and flush_pairs().