Macaulay2 Engine: gbB::spair_delete
spair_delete()
void gbB::spair_delete (spair *& p) private
Definition at line 347 of file gb-test1.cpp.
 {
   if (p == 0) return;
   if (p->type == SPAIR_GEN || p->type == SPAIR_ELEM)
     {
       R->gbvector_remove(p->x.f.f);
       R->gbvector_remove(p->x.f.fsyz);
     }
   R->gbvector_remove(p->lead_of_spoly);
   lcm_stash->delete_elem(p->lcm);
   spair_stash->delete_elem(p);
 }
References stash::delete_elem(), GBRing::gbvector_remove(), lcm_stash, p, R, SPAIR_ELEM, SPAIR_GEN, and spair_stash.
Referenced by flush_pairs(), minimalize_pairs(), process_spair(), remove_spair_list(), and remove_unneeded_pairs().