Macaulay2 Engine: gbB::insert_gb
insert_gb()
void gbB::insert_gb (POLY f, gbelem_type minlevel) private
Definition at line 1409 of file gb-test1.cpp.
 {
   /* Reduce this element as far as possible.  This either removes content,
      makes it monic, or at least negates it so the lead coeff is positive. */
   ring_elem junk;
   // DEBUG BLOCK  int fwt;
   //  int fdeg = weightInfo->gbvector_weight(f.f, fwt);
   //  fprintf(stderr, "inserting GB element %d, thisdeg %d deg %d gap %d\n",
   //      gb.size(),
   //      this_degree,
   //      fdeg,
   //      fdeg-fwt);
   remainder(f, this_degree, false, junk);
   //  fdeg = weightInfo->gbvector_weight(f.f, fwt);
   //  fprintf(stderr, "    after remainder deg %d gap %d\n",
   //      fdeg,
   //      fdeg-fwt);
   stats_ngb++;
   // Complete hack for getting bug fix to get test/isSubset.m2 to work again for
   // 1.3:
   // over ZZ, always make gb elements non reducers...
   gbelem *g = gbelem_make(f.f, f.fsyz, minlevel, this_degree);
   minimal_gb_valid = false;
   int me = INTSIZE(gb);
   gb.push_back(g);
   n_gb++;
   int x = g->g.f->comp;
   // In a encoded Schreyer order, the following line might miss subring
   // elements.
   // But it at least won't be incorrect...
   if (R->get_flattened_monoid()->in_subring(1, g->g.f->monom)) n_subring++;
   lookup->insert(g->lead, x, me);
   if (M2_gbTrace == 15)
     {
       buffer o;
       o << "    new ";
       gbelem_text_out(o, INTSIZE(gb) - 1);
       emit_line(o.str());
     }
   else if (M2_gbTrace >= 5)
     {
       char s[100];
       buffer o;
       sprintf(s, "new-inserting element %d (minimal %d): ", me, minlevel);
       o << s;
       R->gbvector_text_out(o, F, g->g.f);
       emit_line(o.str());
       o.reset();
       o << "                          syzygy : ";
       R->gbvector_text_out(o, Fsyz, g->g.fsyz);
       emit_line(o.str());
     }
   auto_reduce_by(me);
   if (hilbert)
     {
       bool is_last_elem = hilbert->addMonomial(g->lead, x);
       if (is_last_elem) flush_pairs();
     }
   else
     {
 #ifdef DEVELOPMENT
 #warning "todo: codimension stop condition"
 #endif
       // codim test is set.  Compute the codimension now.
     }
   if (M2_gbTrace >= 10)
     {
       //      show();
     }
 }
References HilbertController::addMonomial(), auto_reduce_by(), gbvector::comp, emit_line(), POLY::f, F, flush_pairs(), POLY::fsyz, Fsyz, gbB::gbelem::g, gb, gbelem_make(), gbelem_text_out(), GBRing::gbvector_text_out(), GBRing::get_flattened_monoid(), hilbert, Monoid::in_subring(), MonomialTable::insert(), INTSIZE, gbB::gbelem::lead, lookup, M2_gbTrace, minimal_gb_valid, gbvector::monom, n_gb, n_subring, R, remainder(), buffer::reset(), stats_ngb, buffer::str(), this_degree, and x.
Referenced by process_spair(), and reduceit().