Macaulay2 Engine: gbB::spair_make_skew
spair_make_skew()
gbB::spair * gbB::spair_make_skew (int i, int v) private
Definition at line 395 of file gb-test1.cpp.
 {
   spair *result;
   int j;
   gbelem *g1 = gb[i];
   exponents exp1 = g1->lead;
   exponents exp2 = exponents_make();
   int vvar = R->skew_variable(v);
   for (j = 0; j < nvars; j++) exp2[j] = 0;
   exp2[vvar] = 2;
   result = spair_node();
   result->next = 0;
   result->type = SPAIR_SKEW;
   result->lcm = exp2;
   exponents_lcm(nvars, g1->deg, exp1, exp2, exp2, gb_weights, result->deg);
   result->x.pair.i = i;
   result->x.pair.j = v;
   return result;
 }
References gbB::gbelem::deg, gbB::spair::deg, mpfr::exp2(), exponents_lcm(), exponents_make(), gb, gb_weights, gbB::spair::lcm, gbB::gbelem::lead, gbB::spair::next, nvars, gbB::spair::pair, R, GBRing::skew_variable(), spair_node(), SPAIR_SKEW, gbB::spair::type, and gbB::spair::x.
Referenced by update_pairs().