Macaulay2 Engine: gbB::spair_make_gen
spair_make_gen()
gbB::spair * gbB::spair_make_gen (POLY f) private
Definition at line 379 of file gb-test1.cpp.
 {
   assert(f.f != 0);
   exponents exp1 = exponents_make();
   R->gbvector_get_lead_exponents(F, f.f, exp1);
   int deg = weightInfo->gbvector_weight(f.f);
   spair *result = spair_node();
   result->next = 0;
   result->type = SPAIR_GEN;
   result->deg = deg;
   result->lcm = exp1;
   result->x.f = f;
   return result;
 }
References gbB::spair::deg, exponents_make(), POLY::f, gbB::spair::f, F, GBRing::gbvector_get_lead_exponents(), GBWeight::gbvector_weight(), gbB::spair::lcm, gbB::spair::next, R, SPAIR_GEN, spair_node(), gbB::spair::type, weightInfo, and gbB::spair::x.
Referenced by new_gen().