Macaulay2 Engine: gbB::auto_reduce_by
auto_reduce_by()
void gbB::auto_reduce_by (int id) private
Definition at line 1367 of file gb-test1.cpp.
 {
   /* Loop backwards while degree doesn't change */
   /* Don't change quotient ring elements */
   gbelem *me = gb[id];
   int a = me->gap;  // Only auto reduce those that are of the same degree
                     // and not a higher gap level
   for (int i = INTSIZE(gb) - 1; i >= first_gb_element; i--)
     {
       if (i == id) continue;
       gbelem *g = gb[i];
       if (g->deg < me->deg) return;
       if (g->gap < a) continue;
       if (M2_gbTrace >= 10)
         {
           buffer o;
           o << "  auto reduce " << i << " by " << id;
           emit_line(o.str());
         }
       R->gbvector_auto_reduce(F,
                               Fsyz,
                               g->g.f,
                               g->g.fsyz,  // these are modified
                               me->g.f,
                               me->g.fsyz);
     }
 }
References gbB::gbelem::deg, emit_line(), POLY::f, F, first_gb_element, POLY::fsyz, Fsyz, gbB::gbelem::g, gbB::gbelem::gap, gb, GBRing::gbvector_auto_reduce(), INTSIZE, M2_gbTrace, R, and buffer::str().
Referenced by insert_gb().