Macaulay2 Engine: gbB::collect_syzygy
collect_syzygy()
void gbB::collect_syzygy (gbvector * fsyz) private
Definition at line 1395 of file gb-test1.cpp.
 {
   _syz.push_back(f);
   n_syz++;
   if (M2_gbTrace >= 10)
     {
       buffer o;
       o << " new syzygy : ";
       R->gbvector_text_out(o, Fsyz, f, 3);
       emit_line(o.str());
     }
 }
References _syz, emit_line(), Fsyz, GBRing::gbvector_text_out(), M2_gbTrace, n_syz, R, and buffer::str().
Referenced by new_gen(), and process_spair().