Macaulay2 Engine: gbB::new_gen
new_gen()
gbB::spair * gbB::new_gen (int i, gbvector * f, ring_elem denom) private
Definition at line 159 of file gb-test1.cpp.
 {
   gbvector *fsyz;
   if (i < n_rows_per_syz)
     fsyz = R->gbvector_term(Fsyz, denom, i + 1);
   else
     fsyz = R->gbvector_zero();
   if (R->gbvector_is_zero(f))
     {
       originalR->get_quotient_info()->gbvector_normal_form(Fsyz, fsyz);
       if (!R->gbvector_is_zero(fsyz))
         {
           // vec fsyzvec = _GR->gbvector_to_vec(Fsyz,fsyz);
           collect_syzygy(fsyz);
         }
       return NULL;
     }
   POLY g;
   g.f = f;
   g.fsyz = fsyz;
   return spair_make_gen(g);
 }
References collect_syzygy(), POLY::f, POLY::fsyz, Fsyz, GBRing::gbvector_is_zero(), QRingInfo::gbvector_normal_form(), GBRing::gbvector_term(), GBRing::gbvector_zero(), PolynomialRing::get_quotient_info(), n_rows_per_syz, originalR, R, and spair_make_gen().
Referenced by initialize().