Macaulay2 Engine: gbB::spair_set_defer
spair_set_defer()
void gbB::spair_set_defer (spair *& p) private
Definition at line 864 of file gb-test1.cpp.
 {
   if (M2_gbTrace == 15)
     {
       emit_line("    deferred by reduction count");
     }
   else if (M2_gbTrace >= 4)
     emit_wrapped("D");
   //  spair_delete(p); // ONLY FOR TESTING!! THIS IS INCORRECT!!
   //  return;
   S->n_in_degree++;
   if (p->type == SPAIR_GEN)
     {
       S->gen_last_deferred->next = p;
       S->gen_last_deferred = p;
     }
   else
     {
       S->spair_last_deferred->next = p;
       S->spair_last_deferred = p;
     }
 }
References emit_line(), emit_wrapped(), gbB::SPairSet::gen_last_deferred, M2_gbTrace, gbB::SPairSet::n_in_degree, gbB::spair::next, p, S, SPAIR_GEN, and gbB::SPairSet::spair_last_deferred.
Referenced by reduceit().