Macaulay2 Engine: Computation::cast_to_ResolutionComputation
cast_to_ResolutionComputation()
virtual ResolutionComputation* Computation::cast_to_ResolutionComputation () inline virtual
Reimplemented in ResolutionComputation.
Definition at line 61 of file comp.hpp.
 { return nullptr; }
Referenced by rawResolutionBetti(), rawResolutionGetFree(), rawResolutionGetMatrix(), and rawResolutionGetMatrix2().