Macaulay2 Engine: M2::RingQQ::create
create()
static RingQQ* M2::RingQQ::create (const ARingQQ * R0) inline static
Definition at line 504 of file aring-glue.hpp.
   {
     RingQQ *result = new RingQQ(R0);
     result->initialize_ring(R0->characteristic());
     result->declare_field();
     result->zeroV = result->from_long(0);
     result->oneV = result->from_long(1);
     result->minus_oneV = result->from_long(-1);
     return result;
   }
References M2::ARingQQGMP::characteristic(), Ring::declare_field(), M2::ConcreteRing< RingType >::from_long(), Ring::initialize_ring(), Ring::minus_oneV, Ring::oneV, RingQQ(), and Ring::zeroV.
Referenced by initializeRationalRing().