Macaulay2 Engine: DetComputation::detmult
detmult()
ring_elem DetComputation::detmult (ring_elem f1, ring_elem g1, ring_elem f2, ring_elem g2, ring_elem d) private
Definition at line 192 of file det.cpp.
 {
   ring_elem a = R->mult(f1, g1);
   ring_elem b = R->mult(f2, g2);
   R->subtract_to(a, b);
   if (!R->is_zero(d))
     {
       ring_elem tmp = R->divide(a, d);  // exact division
       R->remove(a);
       a = tmp;
     }
   R->remove(g1);
   return a;
 }
References Ring::divide(), Ring::is_zero(), Ring::mult(), R, Ring::remove(), and Ring::subtract_to().
Referenced by gauss().