Macaulay2 Engine: MinimalPrimes::codimension
codimension() [1/2]
int MinimalPrimes::codimension ()
Definition at line 28 of file monideal-minprimes.cpp.
 {
   minprime_limit = -1;
   codim_limit = min_codim;
   exps[0] = newarray_atomic_clear(int, nvars);
   ass_prime_generator(mi->first_node(), 0);
   state = do_primes;
   return codim_limit;
 }
References ass_prime_generator(), codim_limit, do_primes, exps, MonomialIdeal::first_node(), mi, min_codim, minprime_limit, newarray_atomic_clear, nvars, and state.
Referenced by IM2_MonomialIdeal_codim().