Macaulay2 Engine: queue::remove
remove()
template<class T > bool queue< T >::remove (T & elem)
Definition at line 131 of file queue.hpp.
 {
   if (len == 0) return false;
   elem = head->entries[head_i];
   head_i++;
   len--;
   if (head == tail)
     {
       if (head_i == tail_i)
         {
           delete head;
           head = NULL;
           len = head_i = tail_i = 0;
         }
     }
   else if (head_i >= block_size)
     {
       queue_block<T> *temp = head;
       head = head->next;
       delete temp;
       head_i = 0;
     }
   return true;
 }
Referenced by GBinhom_comp::find_pairs(), GB_comp::find_pairs(), gb2_comp::find_pairs(), MonomialIdeal::MonomialIdeal(), GBKernelComputation::new_pairs(), res_comp::new_pairs(), res2_comp::new_pairs(), and res_comp::skeleton_pairs().