[buildpackage]
pristine-tar = True
# need M2-emacs submodule
preexport = git submodule init M2/Macaulay2/editors/emacs &&
  git submodule update
postexport = SOURCE_DIR=`echo $GBP_GIT_DIR | sed 's/\/\.git//'` &&
  cp -r $SOURCE_DIR/M2/Macaulay2/editors/emacs/* \
    $GBP_TMP_DIR/M2/Macaulay2/editors/emacs
