Document: macaulay2
Title: Debian macaulay2 Manual
Author: <insert document author here>
Abstract: This manual describes what macaulay2 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/macaulay2/macaulay2.sgml.gz

Format: postscript
Files: /usr/share/doc/macaulay2/macaulay2.ps.gz

Format: text
Files: /usr/share/doc/macaulay2/macaulay2.text.gz

Format: HTML
Index: /usr/share/doc/macaulay2/html/index.html
Files: /usr/share/doc/macaulay2/html/*.html
