Macaulay2 Engine: rawARingGFCoefficients
rawARingGFCoefficients()
M2_arrayintOrNull rawARingGFCoefficients (const RingElement * f)
Definition at line 270 of file aring.cpp.
 {
 #if 1
   const M2::ConcreteRing<M2::ARingGFGivaro> *RGF =
       dynamic_cast<const M2::ConcreteRing<M2::ARingGFGivaro> *>(f->get_ring());
   if (RGF == 0)
     {
       ERROR("expected a GaloisField");
       return 0;
     }
   const M2::ARingGFGivaro &A = RGF->ring();
   M2::ARingGFGivaro::ElementType a;
   A.from_ring_elem(a, f->get_value());
   return A.fieldElementToM2Array(a);
 #else
   ERROR("add --enable-fflas-ffpack --enable-givaro when building M2");
   return 0;
 #endif
 }
References ERROR(), M2::ARingGFGivaro::fieldElementToM2Array(), M2::ARingGFGivaro::from_ring_elem(), RingElement::get_ring(), RingElement::get_value(), and M2::ConcreteRing< RingType >::ring().