Macaulay2 Engine: SchurRing2::mult_by_coefficient
mult_by_coefficient()
schur_poly * SchurRing2::mult_by_coefficient (ring_elem a, const schur_poly * f) const
Definition at line 593 of file schur2.cpp.
 {
   schur_poly *result = new schur_poly;
   VECTOR(ring_elem)::iterator c_result;
   for (VECTOR(ring_elem)::const_iterator c_f = f->coeffs.begin();
        c_f != f->coeffs.end();
        ++c_f)
     result->coeffs.push_back(coefficientRing->mult(a, *c_f));
   result->monoms.insert(
       result->monoms.end(), f->monoms.begin(), f->monoms.end());
   return result;
 }
References coefficientRing, schur_poly::coeffs, schur_poly::monoms, Ring::mult(), and VECTOR().
Referenced by mult().