Macaulay2 Engine: MonomialIdeal::n_pure_powers
n_pure_powers()
int MonomialIdeal::n_pure_powers () const
Definition at line 887 of file monideal.cpp.
 {
   int npure = 0;
   int v, e;
   for (Index<MonomialIdeal> i = first(); i.valid(); i++)
     {
       int *m = operator[](i)->monom().raw();
       if (varpower::is_pure_power(m, v, e)) npure++;
     }
   return npure;
 }
References first(), varpower::is_pure_power(), int_bag::monom(), operator[](), and intarray::raw().