Macaulay2 Engine: MonomialIdeal::find_all_divisors
find_all_divisors()
void MonomialIdeal::find_all_divisors (const int * exp, std::vector< Bag *, gc_allocator< Bag * >> & b) const
Definition at line 213 of file monideal.cpp.
 {
   b.clear();
   if (mi == NULL) return;
   Nmi_node *p = mi;
   for (;;)
     {
       p = p->right;
       if (p == p->header)
         {
           if ((p = p->down()) == NULL) return;
           continue;
         }
       if (p->exp > exp[p->var])
         {
           if ((p = p->header->down()) == NULL) return;
           continue;
         }
       if (p->tag == Nmi_node::leaf)
         {
           b.push_back(p->baggage());
         }
       else
         p = p->down();
     }
 }
References mpfr::exp(), Nmi_node::leaf, mi, and p.
Referenced by GBKernelComputation::find_divisor(), res2_comp::find_divisor(), and Matrix::koszul_monomials().