Macaulay2 Engine: MonomialIdeal::is_equal
is_equal()
bool MonomialIdeal::is_equal (const MonomialIdeal & mi) const
Definition at line 163 of file monideal.cpp.
 {
   if (this == &mi0) return true;
   if (length() != mi0.length()) return false;
   Index<MonomialIdeal> i = first();
   Index<MonomialIdeal> j = mi0.first();
   while (i.valid())
     {
       const int *m = operator[](i)->monom().raw();
       const int *n = mi0[j]->monom().raw();
       if (!varpower::is_equal(m, n)) return false;
       i++;
       j++;
     }
   GC_reachable_here(&mi0);
   return true;
 }
References first(), varpower::is_equal(), length(), int_bag::monom(), operator[](), intarray::raw(), and Index< T >::valid().
Referenced by IM2_MonomialIdeal_is_equal().