Macaulay2 Engine: MonomialIdeal::first
first()
Index< MonomialIdeal > MonomialIdeal::first () const inline
Definition at line 215 of file monideal.hpp.
 {
   return Index<MonomialIdeal>(next(reinterpret_cast<void *>(mi)), this);
 }
References mi, and next().
Referenced by MinimalPrimes::alg1_min_primes(), borel(), computeHashValue(), copy(), erase(), GBinhom_comp::find_pairs(), GB_comp::find_pairs(), gb2_comp::find_pairs(), FrobbyAlexanderDual(), intersect(), iquotient_and_sum(), is_borel(), is_equal(), lcm(), n_pure_powers(), GBKernelComputation::new_pairs(), res_comp::new_pairs(), res2_comp::new_pairs(), operator*(), operator+(), partition_table::partition(), popular_var(), quotient(), radical(), sat(), and res_comp::skeleton_pairs().