Macaulay2 Engine: MonomialIdeal::computeHashValue
computeHashValue()
unsigned int MonomialIdeal::computeHashValue () const protected virtual
Implements EngineObject.
Definition at line 7 of file monideal.cpp.
 {
   // Incorporate the length and the first 5 elements
   unsigned int hashval = length();
   int count = 0;
   Index<MonomialIdeal> i = first();
   while (i.valid() and count < 5)
     {
       const int *m = operator[](i)->monom().raw();
       hashval = 4436435 * hashval + varpower::computeHashValue(m);
       i++;
       count++;
     }
   return hashval;
 }
References varpower::computeHashValue(), count, first(), length(), int_bag::monom(), operator[](), intarray::raw(), and Index< T >::valid().