Macaulay2 Engine: MonomialIdeal::MonomialIdeal
MonomialIdeal() [2/3]
MonomialIdeal::MonomialIdeal (const PolynomialRing * R, queue< Bag * > & elems, stash * mi_stash = 0)
Definition at line 117 of file monideal.cpp.
     : R(R0), mi(0), count(0), mi_stash(mi_stash0)
 {
   if (mi_stash == 0)
     {
       count = 1;
       mi_stash = new stash("mi_node", sizeof(Nmi_node));
     }
   VECTOR(queue<Bag *> *) bins;
   Bag *b;
   while (elems.remove(b))
     {
       int d = varpower::simple_degree(b->monom().raw());
       if (d >= bins.size())
         for (int i = bins.size(); i <= d; i++) bins.push_back(NULL);
       if (bins[d] == NULL) bins[d] = new queue<Bag *>;
       bins[d]->insert(b);
     }
   for (int i = 0; i < bins.size(); i++)
     if (bins[i] != NULL)
       {
         while (bins[i]->remove(b)) insert(b);
         delete bins[i];
       }
 }
References count, queue< T >::insert(), insert(), mi_stash, int_bag::monom(), intarray::raw(), queue< T >::remove(), remove(), varpower::simple_degree(), and VECTOR().