Macaulay2 Engine: MonomialIdeal::borel
borel()
MonomialIdeal * MonomialIdeal::borel () const
Definition at line 840 of file monideal.cpp.
 {
   queue<Bag *> new_elems;
   int *bexp = newarray_atomic(int, get_ring()->n_vars());
   for (Index<MonomialIdeal> i = first(); i.valid(); i++)
     {
       Bag *b = operator[](i);
       varpower::to_ntuple(get_ring()->n_vars(), b->monom().raw(), bexp);
       borel1(new_elems, bexp, get_ring()->n_vars() - 1, get_ring()->n_vars());
     }
   MonomialIdeal *result = new MonomialIdeal(get_ring(), new_elems);
   freemem(bexp);
   return result;
 }
References borel1(), first(), freemem(), get_ring(), int_bag::monom(), MonomialIdeal(), newarray_atomic, operator[](), intarray::raw(), and varpower::to_ntuple().
Referenced by IM2_MonomialIdeal_borel().