Macaulay2 Engine: MonomialIdeal::operator*
operator*()
MonomialIdeal * MonomialIdeal::operator* (const MonomialIdeal & G) const
Definition at line 641 of file monideal.cpp.
 {
   queue<Bag *> new_elems;
   for (Index<MonomialIdeal> i = first(); i.valid(); i++)
     for (Index<MonomialIdeal> j = J.first(); j.valid(); j++)
       {
         Bag *b = new Bag(operator[](i)->basis_elem());
         varpower::mult(operator[](i)->monom().raw(),
                        J[j]->monom().raw(),
                        b->monom());
         new_elems.insert(b);
       }
   MonomialIdeal *result = new MonomialIdeal(get_ring(), new_elems);
   GC_reachable_here(&J);
   return result;
 }
References first(), get_ring(), queue< T >::insert(), int_bag::monom(), MonomialIdeal(), and varpower::mult().