Macaulay2 Engine: MonomialIdeal::quotient
quotient() [1/2]
MonomialIdeal * MonomialIdeal::quotient (const int * m) const
Definition at line 694 of file monideal.cpp.
 {
   queue<Bag *> new_elems;
   for (Index<MonomialIdeal> i = first(); i.valid(); i++)
     {
       Bag *b = new Bag(operator[](i)->basis_elem());
       varpower::quotient(operator[](i)->monom().raw(), m, b->monom());
       new_elems.insert(b);
     }
   MonomialIdeal *result = new MonomialIdeal(get_ring(), new_elems);
   return result;
 }
References queue< T >::insert(), int_bag::monom(), varpower::quotient(), and Index< T >::valid().
Referenced by quotient(), rawColonMonomialIdeal1(), and rawColonMonomialIdeal2().