Macaulay2 Engine: MonomialIdeal::operator[]
operator[]()
Bag * MonomialIdeal::operator[] (Index< MonomialIdeal > i) const inline
Definition at line 207 of file monideal.hpp.
 {
   Nmi_node *p = reinterpret_cast<Nmi_node *>(i.val());
   return p->baggage();
 }
References p, and Index< T >::val().
Referenced by borel(), computeHashValue(), is_borel(), is_equal(), n_pure_powers(), and text_out().