var namespace_m2 =
[
    [ "AConcreteRing", "d3/dd1/class_m2_1_1_a_concrete_ring.html", "d3/dd1/class_m2_1_1_a_concrete_ring" ],
    [ "ARingCC", "d1/dfa/class_m2_1_1_a_ring_c_c.html", "d1/dfa/class_m2_1_1_a_ring_c_c" ],
    [ "ARingCCC", "d6/de1/class_m2_1_1_a_ring_c_c_c.html", "d6/de1/class_m2_1_1_a_ring_c_c_c" ],
    [ "ARingGFFlint", "d5/d5f/class_m2_1_1_a_ring_g_f_flint.html", "d5/d5f/class_m2_1_1_a_ring_g_f_flint" ],
    [ "ARingGFFlintBig", "d8/d7a/class_m2_1_1_a_ring_g_f_flint_big.html", "d8/d7a/class_m2_1_1_a_ring_g_f_flint_big" ],
    [ "ARingGFGivaro", "d6/d8d/class_m2_1_1_a_ring_g_f_givaro.html", "d6/d8d/class_m2_1_1_a_ring_g_f_givaro" ],
    [ "ARingGFM2", "dd/df1/class_m2_1_1_a_ring_g_f_m2.html", "dd/df1/class_m2_1_1_a_ring_g_f_m2" ],
    [ "ARingPolynomialStruct", "db/d05/struct_m2_1_1_a_ring_polynomial_struct.html", "db/d05/struct_m2_1_1_a_ring_polynomial_struct" ],
    [ "ARingQQFlint", "dd/d1b/class_m2_1_1_a_ring_q_q_flint.html", "dd/d1b/class_m2_1_1_a_ring_q_q_flint" ],
    [ "ARingQQGMP", "d9/dec/class_m2_1_1_a_ring_q_q_g_m_p.html", "d9/dec/class_m2_1_1_a_ring_q_q_g_m_p" ],
    [ "ARingRR", "d0/d48/class_m2_1_1_a_ring_r_r.html", "d0/d48/class_m2_1_1_a_ring_r_r" ],
    [ "ARingRRi", "dd/d78/class_m2_1_1_a_ring_r_ri.html", "dd/d78/class_m2_1_1_a_ring_r_ri" ],
    [ "ARingRRR", "dd/d9e/class_m2_1_1_a_ring_r_r_r.html", "dd/d9e/class_m2_1_1_a_ring_r_r_r" ],
    [ "ARingTower", "da/d48/class_m2_1_1_a_ring_tower.html", "da/d48/class_m2_1_1_a_ring_tower" ],
    [ "ARingZZ", "d4/dea/class_m2_1_1_a_ring_z_z.html", "d4/dea/class_m2_1_1_a_ring_z_z" ],
    [ "ARingZZGMP", "db/d2e/class_m2_1_1_a_ring_z_z_g_m_p.html", "db/d2e/class_m2_1_1_a_ring_z_z_g_m_p" ],
    [ "ARingZZp", "d6/d13/class_m2_1_1_a_ring_z_zp.html", "d6/d13/class_m2_1_1_a_ring_z_zp" ],
    [ "ARingZZpFFPACK", "da/d73/class_m2_1_1_a_ring_z_zp_f_f_p_a_c_k.html", "da/d73/class_m2_1_1_a_ring_z_zp_f_f_p_a_c_k" ],
    [ "ARingZZpFlint", "d1/d21/class_m2_1_1_a_ring_z_zp_flint.html", "d1/d21/class_m2_1_1_a_ring_z_zp_flint" ],
    [ "ConcreteRing", "d0/d99/class_m2_1_1_concrete_ring.html", "d0/d99/class_m2_1_1_concrete_ring" ],
    [ "DummyRing", "d5/d2d/class_m2_1_1_dummy_ring.html", "d5/d2d/class_m2_1_1_dummy_ring" ],
    [ "GaloisFieldTable", "d5/dab/class_m2_1_1_galois_field_table.html", "d5/dab/class_m2_1_1_galois_field_table" ],
    [ "Reader", "db/dc5/class_m2_1_1_reader.html", "db/dc5/class_m2_1_1_reader" ],
    [ "RElementWrap", "d1/da0/class_m2_1_1_r_element_wrap.html", "d1/da0/class_m2_1_1_r_element_wrap" ],
    [ "RingInterface", "db/d1a/class_m2_1_1_ring_interface.html", null ],
    [ "RingQQ", "d4/d85/class_m2_1_1_ring_q_q.html", "d4/d85/class_m2_1_1_ring_q_q" ]
];