Macaulay2 Engine: borel1
borel1()
static void borel1 (queue< Bag * > & result, int * m, int loc, int nvars) static
Definition at line 818 of file monideal.cpp.
 {
   if (loc == 0)
     {
       Bag *b = new Bag();
       varpower::from_ntuple(nvars, m, b->monom());
       result.insert(b);
     }
   else
     {
       int a = m[loc];
       for (int i = 0; i <= a; i++)
         {
           borel1(result, m, loc - 1, nvars);
           m[loc]--;
           m[loc - 1]++;
         }
       m[loc] += a + 1;
       m[loc - 1] -= a + 1;
     }
 }
References varpower::from_ntuple(), queue< T >::insert(), and int_bag::monom().
Referenced by MonomialIdeal::borel().