name: website
on:
  push:
    branches:
      - doxygen-test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen
      - name: Configure
        run: |
          make -C M2
          cd M2/BUILD && ../../configure
      - name: Build engine documentation
        run: |
          make -C M2/BUILD/Macaulay2/e tinydoc
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: M2/BUILD/Macaulay2/e/doc/tinydoc
