name: html5validator
on:
  push:
    branches:
      - html5validator

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Install html5validator
        run: |
          sudo apt install pipx
          pipx install html5validator
