name: macOS gfortran test
on: push

jobs:
  macos-gfortran:
    runs-on: macos-latest
    steps:
      - run: |
          gcc --version
          brew install gcc
          gcc --version
          gfortran --version
