name: where are gftables??
on: push

jobs:
  where-are-gftables:
    runs-on: macos-13
    steps:
      - name: Install dependencies
        run: brew install Macaulay2/tap/factory
      - name: Find gftables
        run:  |
          brew ls --verbose factory
          echo "===info==="
          brew info factory
          echo "===cellar==="
          brew --cellar factory
          echo "===prefix==="
          ls -l $(brew --prefix factory)
