name: test libnormaliz on macos
on:
  push:
    branches:
      macos-libnormaliz-test

jobs:
  builds:
    runs-on: macos-latest
    steps:
      - name: Install libnormaliz
        run: |
          brew tap Macaulay2/tap
          brew install normaliz
      - name: Build test program
        run: |
          cat << EOF > foo.cpp
          #include <libnormaliz/libnormaliz.h>
          int main(void)
          {
            normaliz::Cone<long long>();
            return 0;
          }
          EOF
          g++ -I$(brew --prefix normaliz)/include foo.cpp -o foo
          ./foo
