name: find mpfr on macos
on: push

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Install mpfr
        run: |
          brew install mpfr
      - name: Find mpfr
        run: |
          find / -name "libmpfr*dylib*"
