name: find mpfr on macos
on: push

jobs:
  build:
    strategy:
      matrix:
        os: [macos-12, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Show values of environment variables
        run: |
          echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH"
          echo "DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH"
          echo "DYLD_FALLBACK_LIBRARY_PATH=$DYLD_FALLBACK_LIBRARY_PATH"
      - name: Run dlopen
        run: |
          cat << EOF > foo.c
          #include <dlfcn.h>
          #include <stdio.h>
          int main(void) {
            if (!dlopen("libfoo.dylib", RTLD_LAZY))
              puts(dlerror());
          return 0;
          }
          EOF

          gcc foo.c -o foo
          echo before:
          ./foo
          export DYLD_LIBRARY_PATH="/usr/local/lib"
          echo after:
          ./foo

