name: find mpfr on macos
on: push

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Show values of environment variables
        run: |
          echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH"
          echo "DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH"
          echo "DYLD_FALLBACK_LIBRARY_PATH=$DYLD_FALLBACK_LIBRARY_PATH"
      - name: Find mpfr
        run: |
          find / -name "libmpfr*dylib*"
