name: msolve test
on:
  push:

jobs:
  msolve-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libtool-bin libtbb-dev libeigen3-dev libboost-dev libboost-regex-dev libmpfr-dev libflint-dev libflint-arb-dev
      - name: Build msolve
        run: |
          cd M2
          make
          cd BUILD
          ../configure --enable-download
          make -C libraries/msolve
      - name: Check msolve
        run: |
          cd M2/BUILD
          make -C libraries/msolve check
