name: Test libnormaliz
on: push

jobs:
  normaliz:
    runs-on: ubuntu-latest
    steps:
      - name: Install libnormaliz
        run: sudo apt-get -y install libnormaliz-dev
      - name: Is ENFNORMALIZ defined?
        run: |
          cat << EOF > foo.cpp
          #include <iostream>
          #include <libnormaliz/libnormaliz.h>
          int main(void)
          {
          #ifdef ENFNORMALIZ
            std::cerr << "w/ enfnormaliz" << std::endl;
          #else
            std::cerr << "w/o enfnormaliz" << std::endl;
          #endif
            return 0;
          }
          EOF
          g++ foo.cpp -o foo
          ./foo
