name: normaliz test
on: push

jobs:
  normaliz-test:
    runs-on: macos-13
    steps:
      - name: Install Macaulay2 and normaliz
        run: |
          brew tap Macaulay2/tap
          brew install M2 normaliz
      - name: Run normaliz
        run: normaliz --version
      - name: Check normaliz in M2
        run: M2 -e 'findProgram("normaliz", Verbose => true); exit 0'
