name: Test script
on: push

jobs:
  script:
    runs-on: macos-latest
    steps:
      - name: Install Macaulay2
        run: |
          brew tap Macaulay2/tap
          brew install M2
          find /opt/homebrew -name "M2"
      - name: Create script
        run: |
          cat << EOF >> foo
          #!/opt/homebrew/Cellar/macaulay2/1.25.06_2.reinstall/bin/M2 --script
          print "Hello, world!"
          EOF
          cat foo
          chmod +x foo
      - name: Run script
        run: ./foo
