name: Test Homebrew
on: push

jobs:
  test-brew:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-13
          - macos-14
          - macos-15
    steps:
      - name: Try installing from M2 tap
        run: |
          brew config
          brew update
          brew tap macaulay2/tap
          brew install --overwrite python
          brew install automake bison boost tbb ccache ctags texinfo llvm make ninja yasm libffi msolve googletest fplll eigen
          brew install --only-dependencies macaulay2/tap/M2
          brew link factory --force
