name: Test Homebrew
on: push

jobs:
  test-brew:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-13
          - macos-14
          - macos-15
    steps:
      - name: Try installing from M2 tap
        run: brew install --only-dependencies macaulay2/tap/M2
