name: Test Homebrew
on: push

jobs:
  test-brew:
    runs-on: macos-14
    steps:
      - name: Test cddlib
        run: |
          brew install cddlib
          echo $(brew --prefix)
          find $(brew --prefix) . -name "setoper.h"
