name: test git branches
on:
  push:
    branches:
      - workflow-test

defaults:
  run:
    working-directory: M2/BUILD/build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test git stuff
        run: |
          git fetch --depth=1 origin development
          git diff --stat origin/development HEAD -- ../../Macaulay2
