name: yacc test
on: push

jobs:
  yacc-test:
    runs-on: macos-13
    steps:
      - name: Install bison
        run: brew install bison
      - name: Test yacc
        run: |
          yacc --version
          bison --version
